image: ghcr.io/maresb/pymc-devcontainer:latest
tasks:
  - name: initialize
    init: |
      # General devcontainer initialization, e.g. pre-commit
      _dev-init.sh

      # Create an empty object for .vscode/settings.json if the file doesn't exist
      mkdir -p .vscode
      [ -f .vscode/settings.json ] || echo "{}" > .vscode/settings.json

      # Set the default interpreter path
      jq '
            .["python.defaultInterpreterPath"] = "/opt/conda/bin/python"
      ' .vscode/settings.json | sponge .vscode/settings.json

      # Install dependencies
      sudo chown "$(id -u):$(id -g)" /opt/conda/conda-meta/history
      micromamba install --yes --name base --file conda-envs/environment-dev.yml

      # Install PyMC
      pip install -e .

    command: |
      # Reinitialize devcontainer for good measure
      _dev-init.sh

      # Install the pre-commit hooks in the background if not already installed
      [ -f ~/.cache/pre-commit/README ] || cp -R /opt/.pre-commit-cache-prebuilt/* ~/.cache/pre-commit/

vscode:
  extensions:
    - eamodio.gitlens
    - ms-python.python
    - ms-pyright.pyright
    - donjayamanne.githistory

github:
  prebuilds:
    # enable for master branch
    master: true
    # enable for other branches (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: false
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: false
