version: 2

sphinx:
    configuration: docs/source/conf.py

python:
   install:
   - method: pip
     path: .

conda:
  environment: "conda-envs/environment-docs.yml"

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-4.10"
  jobs:
    post_install:
      - mamba list
      - which python
      - python -m ipykernel install --user --name pymc-docs
