#!/usr/bin/env bash
# To run the following correctly, you will need a patched version of docutils to enable support for 
# math directives. 
# There is a dummy module in docs named distributions.py that imports all the PyMC likelihoods. 
# By introspection, epydoc finds the related docstrings and creates a tex output. This way, 
# we avoid documenting all the stuff that lives in the real pymc.distributions.py

#epydoc --verbose --debug --config epydoc.conf


# Make manual
cd docs

#cat distributions-module.tex | ./extract.py -s '\\subsection\{Functions\}' -o distributions-module.text
#sed -i -e 's/0\.5\\fboxrule/1pt/g' distributions-module.tex

python rst2latex.py ../README.txt | ./extract.py -s '\\setlength\{\\locallinewidth\}\{\\linewidth\}' -e '\\hypertarget\{installation\}\{\}' -o README.tex
python rst2latex.py ../INSTALL.txt | ./extract.py -s '\\setlength\{\\locallinewidth\}\{\\linewidth\}' -e '\\end\{document\}' -o INSTALL.tex
python rst2latex.py ../pymc/database/README.txt | ./extract.py -s '\\setlength\{\\locallinewidth\}\{\\linewidth\}' -e '\\end\{document\}' -o database.tex

mkdir pdf
# User Guide
pdflatex -output-directory=pdf -interaction batchmode UserGuide
bibtex pdf/UserGuide
pdflatex -output-directory=pdf -interaction batchmode UserGuide
pdflatex -output-directory=pdf -interaction batchmode UserGuide
cp pdf/UserGuide.pdf .

# JSS
pdflatex -output-directory=pdf -interaction batchmode jss_article
bibtex pdf/jss_article
pdflatex -output-directory=pdf -interaction batchmode jss_article
pdflatex -output-directory=pdf -interaction batchmode jss_article
cp pdf/jss_article.pdf .

cd ..
