#!/bin/sh
export CFLAGS="-arch x86_64"
export FFLAGS="-static -ff2c -arch x86_64"
export LDFLAGS="-Wall -undefined dynamic_lookup -bundle -arch x86_64"
export PYTHONPATH="/Library/Python/2.7/site-packages/"
export CC=gcc-4.2
export CXX=g++-4.2
rm -rf build
python setupegg.py bdist_egg
# sudo python setupegg.py develop
