#!/bin/sh
export MACOSX_DEPLOYMENT_TARGET=10.7
export CFLAGS="-arch x86_64"
export FFLAGS="-m64"
export LDFLAGS="-Wall -undefined dynamic_lookup -bundle -arch x86_64"
export PYTHONPATH="/Library/Python/2.6/site-packages/"
rm -rf build
python setup.py config_fc --fcompiler gnu95 build
#sudo python setup.py install
python setupegg.py bdist_egg