#!/bin/sh
export MACOSX_DEPLOYMENT_TARGET=10.7
export CFLAGS="-arch x86_64"
export FFLAGS="-static -ff2c"
export LDFLAGS="-Wall -undefined dynamic_lookup -bundle -arch x86_64"
export PYTHONPATH="/Library/Python/2.7/site-packages/"
rm -rf build
python setup.py config_fc --fcompiler gfortran build
#sudo python setup.py install
python setupegg.py bdist_egg
# sudo python setupegg.py develop