/* Generated by Pyrex 0.9.5.1a on Tue May  8 14:09:24 2007 */

#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
__PYX_EXTERN_C double pow(double, double);
#include "stdlib.h"
#include "numpy/ndarrayobject.h"


typedef struct {PyObject **p; char *s;} __Pyx_InternTabEntry; /*proto*/
typedef struct {PyObject **p; char *s; long n;} __Pyx_StringTabEntry; /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
static char **__pyx_f;

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static void __Pyx_WriteUnraisable(char *name); /*proto*/

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t); /*proto*/

static int __Pyx_SetVtable(PyObject *dict, void *vtable); /*proto*/

static void __Pyx_AddTraceback(char *funcname); /*proto*/

/* Declarations from PyrexLazyFunction */


struct __pyx_obj_17PyrexLazyFunction_LazyFunction {
  PyObject_HEAD
  struct __pyx_vtabstruct_17PyrexLazyFunction_LazyFunction *__pyx_vtab;
  PyObject *arguments;
  PyObject *fun;
  PyObject *argument_values;
  PyObject *pymc_object_args;
  PyObject *other_args;
  int cache_depth;
  int N_args;
  PyObject *ultimate_args;
  PyObject *ultimate_keys;
  PyObject *ultimate_arg_values;
  void (*(*ultimate_arg_p));
  void (*(*ultimate_keys_p));
  void (*(*ultimate_arg_value_p));
  PyObject *cached_args;
  PyObject *cached_values;
  void (*(*cached_arg_p));
};

struct __pyx_vtabstruct_17PyrexLazyFunction_LazyFunction {
  void ((*get_array_data)(struct __pyx_obj_17PyrexLazyFunction_LazyFunction *));
  int ((*check_argument_caches)(struct __pyx_obj_17PyrexLazyFunction_LazyFunction *));
  void ((*cache)(struct __pyx_obj_17PyrexLazyFunction_LazyFunction *,PyObject *));
};
static struct __pyx_vtabstruct_17PyrexLazyFunction_LazyFunction *__pyx_vtabptr_17PyrexLazyFunction_LazyFunction;

static PyTypeObject *__pyx_ptype_17PyrexLazyFunction_LazyFunction = 0;


/* Implementation of PyrexLazyFunction */


static PyObject *__pyx_n___docformat__;
static PyObject *__pyx_n_array;
static PyObject *__pyx_n_zeros;
static PyObject *__pyx_n_ones;
static PyObject *__pyx_n_arange;
static PyObject *__pyx_n_resize;
static PyObject *__pyx_n_PyMCBase;
static PyObject *__pyx_n_ContainerBase;
static PyObject *__pyx_n_reStructuredText;
static PyObject *__pyx_n_numpy;
static PyObject *__pyx_n_PyMC2;

static PyObject *__pyx_n_iterkeys;
static PyObject *__pyx_n_isinstance;
static PyObject *__pyx_n_value;
static PyObject *__pyx_n_append;
static PyObject *__pyx_n_pymc_objects;
static PyObject *__pyx_n_object;
static PyObject *__pyx_n_dtype;
static PyObject *__pyx_n_len;
static PyObject *__pyx_n_range;


static int __pyx_f_17PyrexLazyFunction_12LazyFunction___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_17PyrexLazyFunction_12LazyFunction___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_fun = 0;
  PyObject *__pyx_v_arguments = 0;
  PyObject *__pyx_v_cache_depth = 0;
  PyObject *__pyx_v_arg;
  PyObject *__pyx_v_name;
  int __pyx_v_i;
  PyObject *__pyx_v_obj;
  int __pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  PyObject *__pyx_6 = 0;
  static char *__pyx_argnames[] = {"fun","arguments","cache_depth",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOO", __pyx_argnames, &__pyx_v_fun, &__pyx_v_arguments, &__pyx_v_cache_depth)) return -1;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_fun);
  Py_INCREF(__pyx_v_arguments);
  Py_INCREF(__pyx_v_cache_depth);
  __pyx_v_arg = Py_None; Py_INCREF(Py_None);
  __pyx_v_name = Py_None; Py_INCREF(Py_None);
  __pyx_v_obj = Py_None; Py_INCREF(Py_None);

  /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":85 */
  Py_INCREF(__pyx_v_arguments);
  Py_DECREF(((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->arguments);
  ((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->arguments = __pyx_v_arguments;

  /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":87 */
  __pyx_1 = PyInt_AsLong(__pyx_v_cache_depth); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 87; goto __pyx_L1;}
  ((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->cache_depth = __pyx_1;

  /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":91 */
  __pyx_2 = PyDict_New(); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; goto __pyx_L1;}
  Py_DECREF(((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->pymc_object_args);
  ((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->pymc_object_args = __pyx_2;
  __pyx_2 = 0;

  /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":93 */
  __pyx_2 = PyDict_New(); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 93; goto __pyx_L1;}
  Py_DECREF(((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->other_args);
  ((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->other_args = __pyx_2;
  __pyx_2 = 0;

  /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":97 */
  __pyx_2 = PyList_New(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 97; goto __pyx_L1;}
  Py_DECREF(((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->ultimate_args);
  ((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->ultimate_args = __pyx_2;
  __pyx_2 = 0;

  /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":99 */
  __pyx_2 = PyList_New(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; goto __pyx_L1;}
  Py_DECREF(((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->ultimate_keys);
  ((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->ultimate_keys = __pyx_2;
  __pyx_2 = 0;

  /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":102 */
  __pyx_2 = PyDict_New(); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 102; goto __pyx_L1;}
  Py_DECREF(((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->argument_values);
  ((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->argument_values = __pyx_2;
  __pyx_2 = 0;

  /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":105 */
  __pyx_2 = PyObject_GetAttr(__pyx_v_arguments, __pyx_n_iterkeys); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 105; goto __pyx_L1;}
  __pyx_3 = PyObject_CallObject(__pyx_2, 0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 105; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_2 = PyObject_GetIter(__pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 105; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  for (;;) {
    __pyx_3 = PyIter_Next(__pyx_2);
    if (!__pyx_3) {
      if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 105; goto __pyx_L1;}
      break;
    }
    Py_DECREF(__pyx_v_name);
    __pyx_v_name = __pyx_3;
    __pyx_3 = 0;

    /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":108 */
    __pyx_3 = PyObject_GetItem(__pyx_v_arguments, __pyx_v_name); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 108; goto __pyx_L1;}
    Py_DECREF(__pyx_v_arg);
    __pyx_v_arg = __pyx_3;
    __pyx_3 = 0;

    /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":112 */
    __pyx_3 = __Pyx_GetName(__pyx_b, __pyx_n_isinstance); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 112; goto __pyx_L1;}
    __pyx_4 = __Pyx_GetName(__pyx_m, __pyx_n_ContainerBase); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 112; goto __pyx_L1;}
    __pyx_5 = PyTuple_New(2); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 112; goto __pyx_L1;}
    Py_INCREF(__pyx_v_arg);
    PyTuple_SET_ITEM(__pyx_5, 0, __pyx_v_arg);
    PyTuple_SET_ITEM(__pyx_5, 1, __pyx_4);
    __pyx_4 = 0;
    __pyx_4 = PyObject_CallObject(__pyx_3, __pyx_5); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 112; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    __pyx_1 = PyObject_IsTrue(__pyx_4); if (__pyx_1 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 112; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    if (__pyx_1) {

      /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":114 */
      __pyx_3 = PyObject_GetAttr(__pyx_v_arg, __pyx_n_value); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 114; goto __pyx_L1;}
      if (PyObject_SetItem(((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->argument_values, __pyx_v_name, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 114; goto __pyx_L1;}
      Py_DECREF(__pyx_3); __pyx_3 = 0;

      /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":115 */
      __pyx_5 = PyObject_GetAttr(((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->ultimate_args, __pyx_n_append); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; goto __pyx_L1;}
      __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; goto __pyx_L1;}
      Py_INCREF(__pyx_v_arg);
      PyTuple_SET_ITEM(__pyx_4, 0, __pyx_v_arg);
      __pyx_3 = PyObject_CallObject(__pyx_5, __pyx_4); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; goto __pyx_L1;}
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      Py_DECREF(__pyx_4); __pyx_4 = 0;
      Py_DECREF(__pyx_3); __pyx_3 = 0;

      /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":116 */
      __pyx_5 = PyObject_GetAttr(((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->ultimate_keys, __pyx_n_append); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 116; goto __pyx_L1;}
      __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 116; goto __pyx_L1;}
      Py_INCREF(__pyx_v_arg);
      PyTuple_SET_ITEM(__pyx_4, 0, __pyx_v_arg);
      __pyx_3 = PyObject_CallObject(__pyx_5, __pyx_4); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 116; goto __pyx_L1;}
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      Py_DECREF(__pyx_4); __pyx_4 = 0;
      Py_DECREF(__pyx_3); __pyx_3 = 0;

      /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":118 */
      __pyx_5 = PyObject_GetAttr(__pyx_v_arg, __pyx_n_pymc_objects); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 118; goto __pyx_L1;}
      __pyx_4 = PyObject_GetIter(__pyx_5); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 118; goto __pyx_L1;}
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      for (;;) {
        __pyx_3 = PyIter_Next(__pyx_4);
        if (!__pyx_3) {
          if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 118; goto __pyx_L1;}
          break;
        }
        Py_DECREF(__pyx_v_obj);
        __pyx_v_obj = __pyx_3;
        __pyx_3 = 0;

        /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":119 */
        __pyx_5 = PyObject_GetAttr(((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->ultimate_args, __pyx_n_append); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 119; goto __pyx_L1;}
        __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 119; goto __pyx_L1;}
        Py_INCREF(__pyx_v_obj);
        PyTuple_SET_ITEM(__pyx_3, 0, __pyx_v_obj);
        __pyx_6 = PyObject_CallObject(__pyx_5, __pyx_3); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 119; goto __pyx_L1;}
        Py_DECREF(__pyx_5); __pyx_5 = 0;
        Py_DECREF(__pyx_3); __pyx_3 = 0;
        Py_DECREF(__pyx_6); __pyx_6 = 0;

        /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":120 */
        __pyx_5 = PyObject_GetAttr(((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->ultimate_keys, __pyx_n_append); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 120; goto __pyx_L1;}
        __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 120; goto __pyx_L1;}
        Py_INCREF(Py_None);
        PyTuple_SET_ITEM(__pyx_3, 0, Py_None);
        __pyx_6 = PyObject_CallObject(__pyx_5, __pyx_3); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 120; goto __pyx_L1;}
        Py_DECREF(__pyx_5); __pyx_5 = 0;
        Py_DECREF(__pyx_3); __pyx_3 = 0;
        Py_DECREF(__pyx_6); __pyx_6 = 0;
      }
      Py_DECREF(__pyx_4); __pyx_4 = 0;
      goto __pyx_L4;
    }
    __pyx_5 = __Pyx_GetName(__pyx_b, __pyx_n_isinstance); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 124; goto __pyx_L1;}
    __pyx_3 = __Pyx_GetName(__pyx_m, __pyx_n_PyMCBase); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 124; goto __pyx_L1;}
    __pyx_6 = PyTuple_New(2); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 124; goto __pyx_L1;}
    Py_INCREF(__pyx_v_arg);
    PyTuple_SET_ITEM(__pyx_6, 0, __pyx_v_arg);
    PyTuple_SET_ITEM(__pyx_6, 1, __pyx_3);
    __pyx_3 = 0;
    __pyx_4 = PyObject_CallObject(__pyx_5, __pyx_6); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 124; goto __pyx_L1;}
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    __pyx_1 = PyObject_IsTrue(__pyx_4); if (__pyx_1 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 124; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    if (__pyx_1) {

      /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":125 */
      if (PyObject_SetItem(((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->pymc_object_args, __pyx_v_name, __pyx_v_arg) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 125; goto __pyx_L1;}

      /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":126 */
      __pyx_3 = PyObject_GetAttr(((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->ultimate_args, __pyx_n_append); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 126; goto __pyx_L1;}
      __pyx_5 = PyTuple_New(1); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 126; goto __pyx_L1;}
      Py_INCREF(__pyx_v_arg);
      PyTuple_SET_ITEM(__pyx_5, 0, __pyx_v_arg);
      __pyx_6 = PyObject_CallObject(__pyx_3, __pyx_5); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 126; goto __pyx_L1;}
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      Py_DECREF(__pyx_6); __pyx_6 = 0;

      /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":127 */
      __pyx_4 = PyObject_GetAttr(((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->ultimate_keys, __pyx_n_append); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 127; goto __pyx_L1;}
      __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 127; goto __pyx_L1;}
      Py_INCREF(__pyx_v_name);
      PyTuple_SET_ITEM(__pyx_3, 0, __pyx_v_name);
      __pyx_5 = PyObject_CallObject(__pyx_4, __pyx_3); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 127; goto __pyx_L1;}
      Py_DECREF(__pyx_4); __pyx_4 = 0;
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      Py_DECREF(__pyx_5); __pyx_5 = 0;

      /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":128 */
      __pyx_6 = PyObject_GetAttr(__pyx_v_arg, __pyx_n_value); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 128; goto __pyx_L1;}
      if (PyObject_SetItem(((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->argument_values, __pyx_v_name, __pyx_6) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 128; goto __pyx_L1;}
      Py_DECREF(__pyx_6); __pyx_6 = 0;
      goto __pyx_L4;
    }
    /*else*/ {

      /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":133 */
      if (PyObject_SetItem(((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->other_args, __pyx_v_name, __pyx_v_arg) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 133; goto __pyx_L1;}

      /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":134 */
      if (PyObject_SetItem(((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->argument_values, __pyx_v_name, __pyx_v_arg) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 134; goto __pyx_L1;}
    }
    __pyx_L4:;
  }
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":139 */
  __pyx_4 = __Pyx_GetName(__pyx_m, __pyx_n_array); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 139; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 139; goto __pyx_L1;}
  Py_INCREF(((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->ultimate_args);
  PyTuple_SET_ITEM(__pyx_3, 0, ((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->ultimate_args);
  __pyx_5 = PyDict_New(); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 139; goto __pyx_L1;}
  __pyx_6 = __Pyx_GetName(__pyx_b, __pyx_n_object); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 139; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_5, __pyx_n_dtype, __pyx_6) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 139; goto __pyx_L1;}
  Py_DECREF(__pyx_6); __pyx_6 = 0;
  __pyx_2 = PyEval_CallObjectWithKeywords(__pyx_4, __pyx_3, __pyx_5); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 139; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  Py_DECREF(((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->ultimate_args);
  ((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->ultimate_args = __pyx_2;
  __pyx_2 = 0;

  /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":140 */
  __pyx_6 = __Pyx_GetName(__pyx_m, __pyx_n_array); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 140; goto __pyx_L1;}
  __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 140; goto __pyx_L1;}
  Py_INCREF(((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->ultimate_keys);
  PyTuple_SET_ITEM(__pyx_4, 0, ((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->ultimate_keys);
  __pyx_3 = PyDict_New(); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 140; goto __pyx_L1;}
  __pyx_5 = __Pyx_GetName(__pyx_b, __pyx_n_object); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 140; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_3, __pyx_n_dtype, __pyx_5) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 140; goto __pyx_L1;}
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  __pyx_2 = PyEval_CallObjectWithKeywords(__pyx_6, __pyx_4, __pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 140; goto __pyx_L1;}
  Py_DECREF(__pyx_6); __pyx_6 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->ultimate_keys);
  ((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->ultimate_keys = __pyx_2;
  __pyx_2 = 0;

  /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":142 */
  __pyx_5 = __Pyx_GetName(__pyx_b, __pyx_n_len); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 142; goto __pyx_L1;}
  __pyx_6 = PyTuple_New(1); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 142; goto __pyx_L1;}
  Py_INCREF(((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->ultimate_args);
  PyTuple_SET_ITEM(__pyx_6, 0, ((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->ultimate_args);
  __pyx_4 = PyObject_CallObject(__pyx_5, __pyx_6); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 142; goto __pyx_L1;}
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  Py_DECREF(__pyx_6); __pyx_6 = 0;
  __pyx_1 = PyInt_AsLong(__pyx_4); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 142; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  ((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->N_args = __pyx_1;

  /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":145 */
  __pyx_3 = __Pyx_GetName(__pyx_m, __pyx_n_zeros); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 145; goto __pyx_L1;}
  __pyx_2 = PyInt_FromLong(((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->N_args); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 145; goto __pyx_L1;}
  __pyx_5 = PyTuple_New(1); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 145; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_5, 0, __pyx_2);
  __pyx_2 = 0;
  __pyx_6 = PyDict_New(); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 145; goto __pyx_L1;}
  __pyx_4 = __Pyx_GetName(__pyx_b, __pyx_n_object); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 145; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_6, __pyx_n_dtype, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 145; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_2 = PyEval_CallObjectWithKeywords(__pyx_3, __pyx_5, __pyx_6); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 145; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  Py_DECREF(__pyx_6); __pyx_6 = 0;
  Py_DECREF(((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->ultimate_arg_values);
  ((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->ultimate_arg_values = __pyx_2;
  __pyx_2 = 0;

  /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":148 */
  __pyx_4 = __Pyx_GetName(__pyx_m, __pyx_n_zeros); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 148; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong((((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->cache_depth * ((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->N_args)); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 148; goto __pyx_L1;}
  __pyx_5 = PyTuple_New(1); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 148; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_5, 0, __pyx_3);
  __pyx_3 = 0;
  __pyx_6 = PyDict_New(); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 148; goto __pyx_L1;}
  __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_object); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 148; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_6, __pyx_n_dtype, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 148; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_3 = PyEval_CallObjectWithKeywords(__pyx_4, __pyx_5, __pyx_6); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 148; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  Py_DECREF(__pyx_6); __pyx_6 = 0;
  Py_DECREF(((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->cached_args);
  ((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->cached_args = __pyx_3;
  __pyx_3 = 0;

  /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":149 */
  __pyx_2 = PyList_New(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 149; goto __pyx_L1;}
  Py_DECREF(((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->cached_values);
  ((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->cached_values = __pyx_2;
  __pyx_2 = 0;

  /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":150 */
  __pyx_4 = __Pyx_GetName(__pyx_b, __pyx_n_range); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 150; goto __pyx_L1;}
  __pyx_5 = PyInt_FromLong(((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->cache_depth); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 150; goto __pyx_L1;}
  __pyx_6 = PyTuple_New(1); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 150; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_6, 0, __pyx_5);
  __pyx_5 = 0;
  __pyx_3 = PyObject_CallObject(__pyx_4, __pyx_6); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 150; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  Py_DECREF(__pyx_6); __pyx_6 = 0;
  __pyx_2 = PyObject_GetIter(__pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 150; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  for (;;) {
    __pyx_5 = PyIter_Next(__pyx_2);
    if (!__pyx_5) {
      if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 150; goto __pyx_L1;}
      break;
    }
    __pyx_1 = PyInt_AsLong(__pyx_5); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 150; goto __pyx_L1;}
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    __pyx_v_i = __pyx_1;

    /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":151 */
    __pyx_4 = PyObject_GetAttr(((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->cached_values, __pyx_n_append); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 151; goto __pyx_L1;}
    __pyx_6 = PyTuple_New(1); if (!__pyx_6) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 151; goto __pyx_L1;}
    Py_INCREF(Py_None);
    PyTuple_SET_ITEM(__pyx_6, 0, Py_None);
    __pyx_3 = PyObject_CallObject(__pyx_4, __pyx_6); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 151; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
  }
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":154 */
  if (PySequence_SetSlice(((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->ultimate_arg_values, 0, 0x7fffffff, Py_None) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 154; goto __pyx_L1;}

  /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":155 */
  if (PySequence_SetSlice(((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->cached_args, 0, 0x7fffffff, Py_None) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 155; goto __pyx_L1;}

  /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":158 */
  Py_INCREF(__pyx_v_fun);
  Py_DECREF(((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->fun);
  ((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->fun = __pyx_v_fun;

  /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":162 */
  ((struct __pyx_vtabstruct_17PyrexLazyFunction_LazyFunction *)((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->__pyx_vtab)->get_array_data(((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self));

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  Py_XDECREF(__pyx_6);
  __Pyx_AddTraceback("PyrexLazyFunction.LazyFunction.__init__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_arg);
  Py_DECREF(__pyx_v_name);
  Py_DECREF(__pyx_v_obj);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_fun);
  Py_DECREF(__pyx_v_arguments);
  Py_DECREF(__pyx_v_cache_depth);
  return __pyx_r;
}

static char (__pyx_k15[]) = "\n        Get underlying pointers from arrays ultimate_args, ultimate_keys,\n        ultimate_arg_values, and cached_args.\n        \n        Although the underlying pointers are PyObject**, they\'re cast to \n        void** because Pyrex doesn\'t let you work with object* pointers.\n        ";

static void __pyx_f_17PyrexLazyFunction_12LazyFunction_get_array_data(struct __pyx_obj_17PyrexLazyFunction_LazyFunction *__pyx_v_self) {
  Py_INCREF(__pyx_v_self);

  /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":166 */
  __pyx_k15;

  /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":173 */
  __pyx_v_self->ultimate_arg_p = ((void (*(*)))PyArray_DATA(__pyx_v_self->ultimate_args));

  /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":174 */
  __pyx_v_self->ultimate_keys_p = ((void (*(*)))PyArray_DATA(__pyx_v_self->ultimate_keys));

  /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":175 */
  __pyx_v_self->ultimate_arg_value_p = ((void (*(*)))PyArray_DATA(__pyx_v_self->ultimate_arg_values));

  /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":176 */
  __pyx_v_self->cached_arg_p = ((void (*(*)))PyArray_DATA(__pyx_v_self->cached_args));

  Py_DECREF(__pyx_v_self);
}

static char (__pyx_k16[]) = "\n        Compare the value of the ultimate arguments to the values in the cache.\n        If there\'s a mismatch (match is by reference, not value), return -1.\n        Otherwise return 0.\n        ";

static int __pyx_f_17PyrexLazyFunction_12LazyFunction_check_argument_caches(struct __pyx_obj_17PyrexLazyFunction_LazyFunction *__pyx_v_self) {
  int __pyx_v_i;
  int __pyx_v_j;
  int __pyx_v_mismatch;
  int __pyx_r;
  int __pyx_1;
  int __pyx_2;
  int __pyx_3;
  Py_INCREF(__pyx_v_self);

  /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":180 */
  __pyx_k16;

  /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":187 */
  __pyx_1 = (__pyx_v_self->cache_depth > 0);
  if (__pyx_1) {

    /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":189 */
    __pyx_1 = __pyx_v_self->cache_depth;
    for (__pyx_v_i = 0; __pyx_v_i < __pyx_1; ++__pyx_v_i) {

      /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":190 */
      __pyx_v_mismatch = 0;

      /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":192 */
      __pyx_2 = __pyx_v_self->N_args;
      for (__pyx_v_j = 0; __pyx_v_j < __pyx_2; ++__pyx_v_j) {

        /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":197 */
        __pyx_3 = (!((__pyx_v_self->ultimate_arg_value_p[__pyx_v_j]) == (__pyx_v_self->cached_arg_p[((__pyx_v_i * __pyx_v_self->N_args) + __pyx_v_j)])));
        if (__pyx_3) {

          /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":198 */
          __pyx_v_mismatch = 1;

          /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":199 */
          goto __pyx_L6;
          goto __pyx_L7;
        }
        __pyx_L7:;
      }
      __pyx_L6:;

      /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":201 */
      __pyx_3 = (__pyx_v_mismatch == 0);
      if (__pyx_3) {

        /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":202 */
        __pyx_r = __pyx_v_i;
        goto __pyx_L0;
        goto __pyx_L8;
      }
      __pyx_L8:;
    }
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":204 */
  __pyx_r = (-1);
  goto __pyx_L0;

  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_17PyrexLazyFunction_12LazyFunction_refresh_argument_values(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_17PyrexLazyFunction_12LazyFunction_refresh_argument_values[] = "\n        Iterates over LazyFunction\'s parents that are Parameters,\n        Nodes, or Containers and records their current values\n        for passing to self\'s internal function.\n        ";
static PyObject *__pyx_f_17PyrexLazyFunction_12LazyFunction_refresh_argument_values(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_item;
  int __pyx_v_i;
  PyObject *__pyx_v_name;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  int __pyx_4;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_v_item = Py_None; Py_INCREF(Py_None);
  __pyx_v_name = Py_None; Py_INCREF(Py_None);

  /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":218 */
  __pyx_1 = ((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->N_args;
  for (__pyx_v_i = 0; __pyx_v_i < __pyx_1; ++__pyx_v_i) {

    /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":222 */
    __pyx_2 = PyInt_FromLong(__pyx_v_i); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 222; goto __pyx_L1;}
    __pyx_3 = PyObject_GetItem(((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->ultimate_args, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 222; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __pyx_2 = PyObject_GetAttr(__pyx_3, __pyx_n_value); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 222; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    Py_DECREF(__pyx_v_item);
    __pyx_v_item = __pyx_2;
    __pyx_2 = 0;

    /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":223 */
    __pyx_3 = PyInt_FromLong(__pyx_v_i); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 223; goto __pyx_L1;}
    if (PyObject_SetItem(((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->ultimate_arg_values, __pyx_3, __pyx_v_item) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 223; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;

    /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":225 */
    __pyx_2 = PyInt_FromLong(__pyx_v_i); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 225; goto __pyx_L1;}
    __pyx_3 = PyObject_GetItem(((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->ultimate_keys, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 225; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_v_name);
    __pyx_v_name = __pyx_3;
    __pyx_3 = 0;

    /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":229 */
    __pyx_4 = __pyx_v_name != Py_None;
    if (__pyx_4) {

      /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":230 */
      if (PyObject_SetItem(((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->argument_values, __pyx_v_name, __pyx_v_item) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 230; goto __pyx_L1;}
      goto __pyx_L4;
    }
    __pyx_L4:;
  }

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("PyrexLazyFunction.LazyFunction.refresh_argument_values");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_item);
  Py_DECREF(__pyx_v_name);
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_n_pop;
static PyObject *__pyx_n_insert;

static char (__pyx_k17[]) = "\n        Stick self\'s value in the cache, and also the values of all self\'s\n        ultimate arguments for future caching.\n        ";

static void __pyx_f_17PyrexLazyFunction_12LazyFunction_cache(struct __pyx_obj_17PyrexLazyFunction_LazyFunction *__pyx_v_self,PyObject *__pyx_v_value) {
  int __pyx_v_i;
  int __pyx_v_j;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  long __pyx_5;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_value);

  /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":234 */
  __pyx_k17;

  /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":240 */
  __pyx_1 = (__pyx_v_self->cache_depth > 0);
  if (__pyx_1) {

    /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":242 */
    __pyx_2 = PyObject_GetAttr(__pyx_v_self->cached_values, __pyx_n_pop); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 242; goto __pyx_L1;}
    __pyx_3 = PyObject_CallObject(__pyx_2, 0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 242; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;

    /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":243 */
    __pyx_2 = PyObject_GetAttr(__pyx_v_self->cached_values, __pyx_n_insert); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 243; goto __pyx_L1;}
    __pyx_3 = PyInt_FromLong(0); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 243; goto __pyx_L1;}
    __pyx_4 = PyTuple_New(2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 243; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_4, 0, __pyx_3);
    Py_INCREF(__pyx_v_value);
    PyTuple_SET_ITEM(__pyx_4, 1, __pyx_v_value);
    __pyx_3 = 0;
    __pyx_3 = PyObject_CallObject(__pyx_2, __pyx_4); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 243; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;

    /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":246 */
    __pyx_5 = (__pyx_v_self->cache_depth - 1);
    for (__pyx_v_i = 0; __pyx_v_i < __pyx_5; ++__pyx_v_i) {

      /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":247 */
      __pyx_1 = __pyx_v_self->N_args;
      for (__pyx_v_j = 0; __pyx_v_j < __pyx_1; ++__pyx_v_j) {

        /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":250 */
        __pyx_2 = PyInt_FromLong(((__pyx_v_i * __pyx_v_self->N_args) + __pyx_v_j)); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 250; goto __pyx_L1;}
        __pyx_4 = PyObject_GetItem(__pyx_v_self->cached_args, __pyx_2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 250; goto __pyx_L1;}
        Py_DECREF(__pyx_2); __pyx_2 = 0;
        __pyx_3 = PyInt_FromLong((((__pyx_v_i + 1) * __pyx_v_self->N_args) + __pyx_v_j)); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 250; goto __pyx_L1;}
        if (PyObject_SetItem(__pyx_v_self->cached_args, __pyx_3, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 250; goto __pyx_L1;}
        Py_DECREF(__pyx_3); __pyx_3 = 0;
        Py_DECREF(__pyx_4); __pyx_4 = 0;
      }
    }

    /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":253 */
    __pyx_1 = __pyx_v_self->N_args;
    for (__pyx_v_j = 0; __pyx_v_j < __pyx_1; ++__pyx_v_j) {

      /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":254 */
      __pyx_2 = PyInt_FromLong(__pyx_v_j); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 254; goto __pyx_L1;}
      __pyx_4 = PyObject_GetItem(__pyx_v_self->ultimate_arg_values, __pyx_2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 254; goto __pyx_L1;}
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      __pyx_3 = PyInt_FromLong(__pyx_v_j); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 254; goto __pyx_L1;}
      if (PyObject_SetItem(__pyx_v_self->cached_args, __pyx_3, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 254; goto __pyx_L1;}
      Py_DECREF(__pyx_3); __pyx_3 = 0;
      Py_DECREF(__pyx_4); __pyx_4 = 0;
    }
    goto __pyx_L2;
  }
  __pyx_L2:;

  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_WriteUnraisable("PyrexLazyFunction.LazyFunction.cache");
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_value);
}

static PyObject *__pyx_n_refresh_argument_values;

static PyObject *__pyx_f_17PyrexLazyFunction_12LazyFunction_force_compute(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_17PyrexLazyFunction_12LazyFunction_force_compute[] = "\n        For debugging purposes. Skip cache checking and compute a value.\n        ";
static PyObject *__pyx_f_17PyrexLazyFunction_12LazyFunction_force_compute(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_value;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_v_value = Py_None; Py_INCREF(Py_None);

  /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":260 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_self, __pyx_n_refresh_argument_values); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 260; goto __pyx_L1;}
  __pyx_2 = PyObject_CallObject(__pyx_1, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 260; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":261 */
  __pyx_1 = PyTuple_New(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 261; goto __pyx_L1;}
  __pyx_2 = PyEval_CallObjectWithKeywords(((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->fun, __pyx_1, ((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->argument_values); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 261; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_v_value);
  __pyx_v_value = __pyx_2;
  __pyx_2 = 0;

  /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":262 */
  ((struct __pyx_vtabstruct_17PyrexLazyFunction_LazyFunction *)((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->__pyx_vtab)->cache(((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self),__pyx_v_value);

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("PyrexLazyFunction.LazyFunction.force_compute");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_value);
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_17PyrexLazyFunction_12LazyFunction_get(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_17PyrexLazyFunction_12LazyFunction_get[] = "\n        Call this method to cause the LazyFunction to refresh its arguments\'\n        values, decide whether it needs to recompute, and return its current\n        value.\n        ";
static PyObject *__pyx_f_17PyrexLazyFunction_12LazyFunction_get(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_v_match_index;
  PyObject *__pyx_v_value;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  int __pyx_3;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_v_value = Py_None; Py_INCREF(Py_None);

  /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":273 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_self, __pyx_n_refresh_argument_values); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 273; goto __pyx_L1;}
  __pyx_2 = PyObject_CallObject(__pyx_1, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 273; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":274 */
  __pyx_v_match_index = ((struct __pyx_vtabstruct_17PyrexLazyFunction_LazyFunction *)((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->__pyx_vtab)->check_argument_caches(((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self));

  /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":277 */
  __pyx_3 = (__pyx_v_match_index < 0);
  if (__pyx_3) {

    /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":280 */
    __pyx_1 = PyTuple_New(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 280; goto __pyx_L1;}
    __pyx_2 = PyEval_CallObjectWithKeywords(((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->fun, __pyx_1, ((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->argument_values); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 280; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    Py_DECREF(__pyx_v_value);
    __pyx_v_value = __pyx_2;
    __pyx_2 = 0;

    /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":282 */
    ((struct __pyx_vtabstruct_17PyrexLazyFunction_LazyFunction *)((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->__pyx_vtab)->cache(((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self),__pyx_v_value);
    goto __pyx_L2;
  }
  /*else*/ {
    __pyx_1 = PyInt_FromLong(__pyx_v_match_index); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 284; goto __pyx_L1;}
    __pyx_2 = PyObject_GetItem(((struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)__pyx_v_self)->cached_values, __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 284; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    Py_INCREF(((PyObject *)__pyx_2));
    Py_DECREF(__pyx_v_value);
    __pyx_v_value = __pyx_2;
    Py_DECREF(__pyx_2); __pyx_2 = 0;
  }
  __pyx_L2:;

  /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":286 */
  Py_INCREF(__pyx_v_value);
  __pyx_r = __pyx_v_value;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("PyrexLazyFunction.LazyFunction.get");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_value);
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static __Pyx_InternTabEntry __pyx_intern_tab[] = {
  {&__pyx_n_ContainerBase, "ContainerBase"},
  {&__pyx_n_PyMC2, "PyMC2"},
  {&__pyx_n_PyMCBase, "PyMCBase"},
  {&__pyx_n___docformat__, "__docformat__"},
  {&__pyx_n_append, "append"},
  {&__pyx_n_arange, "arange"},
  {&__pyx_n_array, "array"},
  {&__pyx_n_dtype, "dtype"},
  {&__pyx_n_insert, "insert"},
  {&__pyx_n_isinstance, "isinstance"},
  {&__pyx_n_iterkeys, "iterkeys"},
  {&__pyx_n_len, "len"},
  {&__pyx_n_numpy, "numpy"},
  {&__pyx_n_object, "object"},
  {&__pyx_n_ones, "ones"},
  {&__pyx_n_pop, "pop"},
  {&__pyx_n_pymc_objects, "pymc_objects"},
  {&__pyx_n_range, "range"},
  {&__pyx_n_reStructuredText, "reStructuredText"},
  {&__pyx_n_refresh_argument_values, "refresh_argument_values"},
  {&__pyx_n_resize, "resize"},
  {&__pyx_n_value, "value"},
  {&__pyx_n_zeros, "zeros"},
  {0, 0}
};
static struct __pyx_vtabstruct_17PyrexLazyFunction_LazyFunction __pyx_vtable_17PyrexLazyFunction_LazyFunction;

static PyObject *__pyx_tp_new_17PyrexLazyFunction_LazyFunction(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = (*t->tp_alloc)(t, 0);
  struct __pyx_obj_17PyrexLazyFunction_LazyFunction *p = (struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)o;
  *(struct __pyx_vtabstruct_17PyrexLazyFunction_LazyFunction **)&p->__pyx_vtab = __pyx_vtabptr_17PyrexLazyFunction_LazyFunction;
  p->arguments = Py_None; Py_INCREF(Py_None);
  p->fun = Py_None; Py_INCREF(Py_None);
  p->argument_values = Py_None; Py_INCREF(Py_None);
  p->pymc_object_args = Py_None; Py_INCREF(Py_None);
  p->other_args = Py_None; Py_INCREF(Py_None);
  p->ultimate_args = Py_None; Py_INCREF(Py_None);
  p->ultimate_keys = Py_None; Py_INCREF(Py_None);
  p->ultimate_arg_values = Py_None; Py_INCREF(Py_None);
  p->cached_args = Py_None; Py_INCREF(Py_None);
  p->cached_values = Py_None; Py_INCREF(Py_None);
  return o;
}

static void __pyx_tp_dealloc_17PyrexLazyFunction_LazyFunction(PyObject *o) {
  struct __pyx_obj_17PyrexLazyFunction_LazyFunction *p = (struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)o;
  Py_XDECREF(p->arguments);
  Py_XDECREF(p->fun);
  Py_XDECREF(p->argument_values);
  Py_XDECREF(p->pymc_object_args);
  Py_XDECREF(p->other_args);
  Py_XDECREF(p->ultimate_args);
  Py_XDECREF(p->ultimate_keys);
  Py_XDECREF(p->ultimate_arg_values);
  Py_XDECREF(p->cached_args);
  Py_XDECREF(p->cached_values);
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_17PyrexLazyFunction_LazyFunction(PyObject *o, visitproc v, void *a) {
  int e;
  struct __pyx_obj_17PyrexLazyFunction_LazyFunction *p = (struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)o;
  if (p->arguments) {
    e = (*v)(p->arguments, a); if (e) return e;
  }
  if (p->fun) {
    e = (*v)(p->fun, a); if (e) return e;
  }
  if (p->argument_values) {
    e = (*v)(p->argument_values, a); if (e) return e;
  }
  if (p->pymc_object_args) {
    e = (*v)(p->pymc_object_args, a); if (e) return e;
  }
  if (p->other_args) {
    e = (*v)(p->other_args, a); if (e) return e;
  }
  if (p->ultimate_args) {
    e = (*v)(p->ultimate_args, a); if (e) return e;
  }
  if (p->ultimate_keys) {
    e = (*v)(p->ultimate_keys, a); if (e) return e;
  }
  if (p->ultimate_arg_values) {
    e = (*v)(p->ultimate_arg_values, a); if (e) return e;
  }
  if (p->cached_args) {
    e = (*v)(p->cached_args, a); if (e) return e;
  }
  if (p->cached_values) {
    e = (*v)(p->cached_values, a); if (e) return e;
  }
  return 0;
}

static int __pyx_tp_clear_17PyrexLazyFunction_LazyFunction(PyObject *o) {
  struct __pyx_obj_17PyrexLazyFunction_LazyFunction *p = (struct __pyx_obj_17PyrexLazyFunction_LazyFunction *)o;
  Py_XDECREF(p->arguments);
  p->arguments = Py_None; Py_INCREF(Py_None);
  Py_XDECREF(p->fun);
  p->fun = Py_None; Py_INCREF(Py_None);
  Py_XDECREF(p->argument_values);
  p->argument_values = Py_None; Py_INCREF(Py_None);
  Py_XDECREF(p->pymc_object_args);
  p->pymc_object_args = Py_None; Py_INCREF(Py_None);
  Py_XDECREF(p->other_args);
  p->other_args = Py_None; Py_INCREF(Py_None);
  Py_XDECREF(p->ultimate_args);
  p->ultimate_args = Py_None; Py_INCREF(Py_None);
  Py_XDECREF(p->ultimate_keys);
  p->ultimate_keys = Py_None; Py_INCREF(Py_None);
  Py_XDECREF(p->ultimate_arg_values);
  p->ultimate_arg_values = Py_None; Py_INCREF(Py_None);
  Py_XDECREF(p->cached_args);
  p->cached_args = Py_None; Py_INCREF(Py_None);
  Py_XDECREF(p->cached_values);
  p->cached_values = Py_None; Py_INCREF(Py_None);
  return 0;
}

static struct PyMethodDef __pyx_methods_17PyrexLazyFunction_LazyFunction[] = {
  {"refresh_argument_values", (PyCFunction)__pyx_f_17PyrexLazyFunction_12LazyFunction_refresh_argument_values, METH_VARARGS|METH_KEYWORDS, __pyx_doc_17PyrexLazyFunction_12LazyFunction_refresh_argument_values},
  {"force_compute", (PyCFunction)__pyx_f_17PyrexLazyFunction_12LazyFunction_force_compute, METH_VARARGS|METH_KEYWORDS, __pyx_doc_17PyrexLazyFunction_12LazyFunction_force_compute},
  {"get", (PyCFunction)__pyx_f_17PyrexLazyFunction_12LazyFunction_get, METH_VARARGS|METH_KEYWORDS, __pyx_doc_17PyrexLazyFunction_12LazyFunction_get},
  {0, 0, 0, 0}
};

static struct PyMemberDef __pyx_members_17PyrexLazyFunction_LazyFunction[] = {
  {"arguments", T_OBJECT, offsetof(struct __pyx_obj_17PyrexLazyFunction_LazyFunction, arguments), 0, 0},
  {"fun", T_OBJECT, offsetof(struct __pyx_obj_17PyrexLazyFunction_LazyFunction, fun), 0, 0},
  {"argument_values", T_OBJECT, offsetof(struct __pyx_obj_17PyrexLazyFunction_LazyFunction, argument_values), 0, 0},
  {"pymc_object_args", T_OBJECT, offsetof(struct __pyx_obj_17PyrexLazyFunction_LazyFunction, pymc_object_args), 0, 0},
  {"other_args", T_OBJECT, offsetof(struct __pyx_obj_17PyrexLazyFunction_LazyFunction, other_args), 0, 0},
  {"ultimate_args", T_OBJECT, offsetof(struct __pyx_obj_17PyrexLazyFunction_LazyFunction, ultimate_args), 0, 0},
  {"ultimate_keys", T_OBJECT, offsetof(struct __pyx_obj_17PyrexLazyFunction_LazyFunction, ultimate_keys), 0, 0},
  {"ultimate_arg_values", T_OBJECT, offsetof(struct __pyx_obj_17PyrexLazyFunction_LazyFunction, ultimate_arg_values), 0, 0},
  {"cached_args", T_OBJECT, offsetof(struct __pyx_obj_17PyrexLazyFunction_LazyFunction, cached_args), 0, 0},
  {"cached_values", T_OBJECT, offsetof(struct __pyx_obj_17PyrexLazyFunction_LazyFunction, cached_values), 0, 0},
  {0, 0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_LazyFunction = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
};

static PySequenceMethods __pyx_tp_as_sequence_LazyFunction = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_LazyFunction = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_LazyFunction = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_17PyrexLazyFunction_LazyFunction = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "PyrexLazyFunction.LazyFunction", /*tp_name*/
  sizeof(struct __pyx_obj_17PyrexLazyFunction_LazyFunction), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_17PyrexLazyFunction_LazyFunction, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_LazyFunction, /*tp_as_number*/
  &__pyx_tp_as_sequence_LazyFunction, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_LazyFunction, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_LazyFunction, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE|Py_TPFLAGS_HAVE_GC, /*tp_flags*/
  "\n    A function that is bound to its arguments, and which caches\n    its last few evaluations so as to skip computation when possible.\n    \n    \n    \n    L = LazyFunction(fun, arguments[, cache_depth])\n    L.get()\n    \n    \n    \n    :Arguments:\n    fun:        The function that the LazyFunction uses to compute its\n                values.\n                \n    arguments:  A dictionary of arguments that the LazyFunction passes\n                to its function. If any of the arguments is a Parameter,\n                Node, or Container, that argument\'s \'value\' attribute\n                will be substituted for it when passed to fun.\n                \n    cache_depth:    The number of prior computations to \'memoize\' in\n                    order to skip unnecessary computations.\n    \n    \n                    \n    Externally-accessible methods:\n    \n    refresh_argument_values():  Iterates over LazyFunction\'s parents that are \n                                Parameters, Nodes, or Containers and records their \n                                current values for passing to self\'s internal \n                                function.\n    \n    get():  Refreshes argument values, checks cache, calls internal function if\n            necessary, returns value.\n            \n    \n    \n    Externally-accessible attributes:\n    \n    arguments:  A dictionary containing self\'s arguments.\n\n    fun:        Self\'s internal function.\n    \n    argument_values:    A dictionary containing self\'s arguments, in which\n                        Parameters, Nodes, and Containers have been\n                        replaced by their \'value\' attributes.\n    \n                \n    \n    :SeeAlso: Parameter, Node, Container\n    ", /*tp_doc*/
  __pyx_tp_traverse_17PyrexLazyFunction_LazyFunction, /*tp_traverse*/
  __pyx_tp_clear_17PyrexLazyFunction_LazyFunction, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_17PyrexLazyFunction_LazyFunction, /*tp_methods*/
  __pyx_members_17PyrexLazyFunction_LazyFunction, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  __pyx_f_17PyrexLazyFunction_12LazyFunction___init__, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_17PyrexLazyFunction_LazyFunction, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC initPyrexLazyFunction(void); /*proto*/
PyMODINIT_FUNC initPyrexLazyFunction(void) {
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  __pyx_init_filenames();
  __pyx_m = Py_InitModule4("PyrexLazyFunction", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 7; goto __pyx_L1;};
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 7; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 7; goto __pyx_L1;};
  if (__Pyx_InternStrings(__pyx_intern_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 7; goto __pyx_L1;};
  __pyx_vtabptr_17PyrexLazyFunction_LazyFunction = &__pyx_vtable_17PyrexLazyFunction_LazyFunction;
  *(void(**)())&__pyx_vtable_17PyrexLazyFunction_LazyFunction.get_array_data = (void(*)())__pyx_f_17PyrexLazyFunction_12LazyFunction_get_array_data;
  *(void(**)())&__pyx_vtable_17PyrexLazyFunction_LazyFunction.check_argument_caches = (void(*)())__pyx_f_17PyrexLazyFunction_12LazyFunction_check_argument_caches;
  *(void(**)())&__pyx_vtable_17PyrexLazyFunction_LazyFunction.cache = (void(*)())__pyx_f_17PyrexLazyFunction_12LazyFunction_cache;
  __pyx_type_17PyrexLazyFunction_LazyFunction.tp_free = _PyObject_GC_Del;
  if (PyType_Ready(&__pyx_type_17PyrexLazyFunction_LazyFunction) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 18; goto __pyx_L1;}
  if (__Pyx_SetVtable(__pyx_type_17PyrexLazyFunction_LazyFunction.tp_dict, __pyx_vtabptr_17PyrexLazyFunction_LazyFunction) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 18; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "LazyFunction", (PyObject *)&__pyx_type_17PyrexLazyFunction_LazyFunction) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 18; goto __pyx_L1;}
  __pyx_ptype_17PyrexLazyFunction_LazyFunction = &__pyx_type_17PyrexLazyFunction_LazyFunction;

  /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":7 */
  if (PyObject_SetAttr(__pyx_m, __pyx_n___docformat__, __pyx_n_reStructuredText) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 7; goto __pyx_L1;}

  /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":9 */
  __pyx_1 = PyList_New(5); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 9; goto __pyx_L1;}
  Py_INCREF(__pyx_n_array);
  PyList_SET_ITEM(__pyx_1, 0, __pyx_n_array);
  Py_INCREF(__pyx_n_zeros);
  PyList_SET_ITEM(__pyx_1, 1, __pyx_n_zeros);
  Py_INCREF(__pyx_n_ones);
  PyList_SET_ITEM(__pyx_1, 2, __pyx_n_ones);
  Py_INCREF(__pyx_n_arange);
  PyList_SET_ITEM(__pyx_1, 3, __pyx_n_arange);
  Py_INCREF(__pyx_n_resize);
  PyList_SET_ITEM(__pyx_1, 4, __pyx_n_resize);
  __pyx_2 = __Pyx_Import(__pyx_n_numpy, __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 9; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyObject_GetAttr(__pyx_2, __pyx_n_array); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 9; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_array, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 9; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyObject_GetAttr(__pyx_2, __pyx_n_zeros); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 9; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_zeros, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 9; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyObject_GetAttr(__pyx_2, __pyx_n_ones); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 9; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_ones, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 9; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyObject_GetAttr(__pyx_2, __pyx_n_arange); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 9; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_arange, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 9; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyObject_GetAttr(__pyx_2, __pyx_n_resize); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 9; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_resize, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 9; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":10 */
  __pyx_2 = PyList_New(2); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 10; goto __pyx_L1;}
  Py_INCREF(__pyx_n_PyMCBase);
  PyList_SET_ITEM(__pyx_2, 0, __pyx_n_PyMCBase);
  Py_INCREF(__pyx_n_ContainerBase);
  PyList_SET_ITEM(__pyx_2, 1, __pyx_n_ContainerBase);
  __pyx_1 = __Pyx_Import(__pyx_n_PyMC2, __pyx_2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 10; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_PyMCBase); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 10; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_PyMCBase, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 10; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_ContainerBase); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 10; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_ContainerBase, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 10; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Users/anand/Documents/renearch/Programming/PyMC/svn/trial/PyMC2/PyrexLazyFunction.pyx":265 */
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("PyrexLazyFunction");
}

static char *__pyx_filenames[] = {
  "PyrexLazyFunction.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list) {
    PyObject *__import__ = 0;
    PyObject *empty_list = 0;
    PyObject *module = 0;
    PyObject *global_dict = 0;
    PyObject *empty_dict = 0;
    PyObject *list;
    __import__ = PyObject_GetAttrString(__pyx_b, "__import__");
    if (!__import__)
        goto bad;
    if (from_list)
        list = from_list;
    else {
        empty_list = PyList_New(0);
        if (!empty_list)
            goto bad;
        list = empty_list;
    }
    global_dict = PyModule_GetDict(__pyx_m);
    if (!global_dict)
        goto bad;
    empty_dict = PyDict_New();
    if (!empty_dict)
        goto bad;
    module = PyObject_CallFunction(__import__, "OOOO",
        name, global_dict, empty_dict, list);
bad:
    Py_XDECREF(empty_list);
    Py_XDECREF(__import__);
    Py_XDECREF(empty_dict);
    return module;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static void __Pyx_WriteUnraisable(char *name) {
    PyObject *old_exc, *old_val, *old_tb;
    PyObject *ctx;
    PyErr_Fetch(&old_exc, &old_val, &old_tb);
    ctx = PyString_FromString(name);
    PyErr_Restore(old_exc, old_val, old_tb);
    if (!ctx)
        ctx = Py_None;
    PyErr_WriteUnraisable(ctx);
}

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t) {
    while (t->p) {
        *t->p = PyString_InternFromString(t->s);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static int __Pyx_SetVtable(PyObject *dict, void *vtable) {
    PyObject *pycobj = 0;
    int result;
    
    pycobj = PyCObject_FromVoidPtr(vtable, 0);
    if (!pycobj)
        goto bad;
    if (PyDict_SetItemString(dict, "__pyx_vtable__", pycobj) < 0)
        goto bad;
    result = 0;
    goto done;

bad:
    result = -1;
done:
    Py_XDECREF(pycobj);
    return result;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
