/* Generated by Pyrex 0.9.4.1 on Wed Dec 19 21:18:38 2007 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)   PyInt_AsLong(o)
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
__PYX_EXTERN_C double pow(double, double);
#include "string.h"
#include "taucs.h"
#include "numpy/ndarrayobject.h"


typedef struct {PyObject **p; char *s;} __Pyx_InternTabEntry; /*proto*/
typedef struct {PyObject **p; char *s; long n;} __Pyx_StringTabEntry; /*proto*/
static PyObject *__Pyx_UnpackItem(PyObject *, Py_ssize_t); /*proto*/
static int __Pyx_EndUnpack(PyObject *, Py_ssize_t); /*proto*/
static int __Pyx_PrintItem(PyObject *); /*proto*/
static int __Pyx_PrintNewline(void); /*proto*/
static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/
static void __Pyx_ReRaise(void); /*proto*/
static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/
static PyObject *__Pyx_GetExcValue(void); /*proto*/
static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed, char *name); /*proto*/
static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type); /*proto*/
static int __Pyx_GetStarArgs(PyObject **args, PyObject **kwds, char *kwd_list[], Py_ssize_t nargs, PyObject **args2, PyObject **kwds2); /*proto*/
static void __Pyx_WriteUnraisable(char *name); /*proto*/
static void __Pyx_AddTraceback(char *funcname); /*proto*/
static PyTypeObject *__Pyx_ImportType(char *module_name, char *class_name, long size);  /*proto*/
static int __Pyx_SetVtable(PyObject *dict, void *vtable); /*proto*/
static int __Pyx_GetVtable(PyObject *dict, void *vtabptr); /*proto*/
static PyObject *__Pyx_CreateClass(PyObject *bases, PyObject *dict, PyObject *name, char *modname); /*proto*/
static int __Pyx_InternStrings(__Pyx_InternTabEntry *t); /*proto*/
static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/
static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
static char **__pyx_f;

/* Declarations from taucs_wrap */

static PyObject *__pyx_k5;
static taucs_ccs_matrix (*(__pyx_f_10taucs_wrap_scipy_to_taucs(PyObject *,char (*),char (*),int ))); /*proto*/
static PyObject *(__pyx_f_10taucs_wrap_taucs_to_scipy(taucs_ccs_matrix (*))); /*proto*/

/* Implementation of taucs_wrap */

static char (__pyx_k1[]) = "scipy.sparse";

static PyObject *__pyx_n_csc_matrix;
static PyObject *__pyx_n_np;
static PyObject *__pyx_n_taucs_factor;
static PyObject *__pyx_n_numpy;
static PyObject *__pyx_n_U;

static PyObject *__pyx_k1p;

static PyObject *__pyx_n_data;
static PyObject *__pyx_n_shape;
static PyObject *__pyx_n_indptr;
static PyObject *__pyx_n_indices;

static char (__pyx_k6[]) = "S";
static char (__pyx_k7[]) = "T";
static char (__pyx_k8[]) = "U";
static char (__pyx_k9[]) = "L";

static taucs_ccs_matrix (*__pyx_f_10taucs_wrap_scipy_to_taucs(PyObject *__pyx_v_CSC,char (*__pyx_v_type),char (*__pyx_v_uplo),int __pyx_v_taucs_type)) {
  int __pyx_v_n;
  int __pyx_v_m;
  int __pyx_v_flags;
  int (*__pyx_v_colptr);
  int (*__pyx_v_rowind);
  double (*__pyx_v_values);
  taucs_ccs_matrix __pyx_v_taucs_out;
  taucs_ccs_matrix (*__pyx_r);
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  int __pyx_4;
  Py_INCREF(__pyx_v_CSC);

  /* "/home/anand/pkgs/RandomRealizations/RandomRealizations/taucs_wrap.pyx":43 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_CSC, __pyx_n_data); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 43; goto __pyx_L1;}
  __pyx_v_values = ((double (*))PyArray_DATA(__pyx_1));
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/anand/pkgs/RandomRealizations/RandomRealizations/taucs_wrap.pyx":46 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_CSC, __pyx_n_shape); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; goto __pyx_L1;}
  __pyx_2 = PyInt_FromLong(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; goto __pyx_L1;}
  __pyx_3 = PyObject_GetItem(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_4 = PyInt_AsLong(__pyx_3); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_v_n = __pyx_4;

  /* "/home/anand/pkgs/RandomRealizations/RandomRealizations/taucs_wrap.pyx":47 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_CSC, __pyx_n_shape); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 47; goto __pyx_L1;}
  __pyx_2 = PyInt_FromLong(0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 47; goto __pyx_L1;}
  __pyx_3 = PyObject_GetItem(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 47; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_4 = PyInt_AsLong(__pyx_3); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 47; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_v_m = __pyx_4;

  /* "/home/anand/pkgs/RandomRealizations/RandomRealizations/taucs_wrap.pyx":50 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_CSC, __pyx_n_indptr); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 50; goto __pyx_L1;}
  __pyx_v_colptr = ((int (*))PyArray_DATA(__pyx_1));
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/anand/pkgs/RandomRealizations/RandomRealizations/taucs_wrap.pyx":51 */
  __pyx_2 = PyObject_GetAttr(__pyx_v_CSC, __pyx_n_indices); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 51; goto __pyx_L1;}
  __pyx_v_rowind = ((int (*))PyArray_DATA(__pyx_2));
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/anand/pkgs/RandomRealizations/RandomRealizations/taucs_wrap.pyx":55 */
  __pyx_v_flags = __pyx_v_taucs_type;

  /* "/home/anand/pkgs/RandomRealizations/RandomRealizations/taucs_wrap.pyx":58 */
  __pyx_4 = (__pyx_v_type == __pyx_k6);
  if (__pyx_4) {

    /* "/home/anand/pkgs/RandomRealizations/RandomRealizations/taucs_wrap.pyx":59 */
    __pyx_v_flags = (__pyx_v_flags | TAUCS_SYMMETRIC);
    goto __pyx_L2;
  }
  __pyx_4 = (__pyx_v_type == __pyx_k7);
  if (__pyx_4) {

    /* "/home/anand/pkgs/RandomRealizations/RandomRealizations/taucs_wrap.pyx":61 */
    __pyx_v_flags = (__pyx_v_flags | TAUCS_TRIANGULAR);
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/home/anand/pkgs/RandomRealizations/RandomRealizations/taucs_wrap.pyx":64 */
  __pyx_4 = (__pyx_v_uplo == __pyx_k8);
  if (__pyx_4) {

    /* "/home/anand/pkgs/RandomRealizations/RandomRealizations/taucs_wrap.pyx":65 */
    __pyx_v_flags = (__pyx_v_flags | TAUCS_UPPER);
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "/home/anand/pkgs/RandomRealizations/RandomRealizations/taucs_wrap.pyx":66 */
  __pyx_4 = (__pyx_v_uplo == __pyx_k9);
  if (__pyx_4) {

    /* "/home/anand/pkgs/RandomRealizations/RandomRealizations/taucs_wrap.pyx":67 */
    __pyx_v_flags = (__pyx_v_flags | TAUCS_LOWER);
    goto __pyx_L4;
  }
  __pyx_L4:;

  /* "/home/anand/pkgs/RandomRealizations/RandomRealizations/taucs_wrap.pyx":70 */
  __pyx_v_taucs_out.n = __pyx_v_n;

  /* "/home/anand/pkgs/RandomRealizations/RandomRealizations/taucs_wrap.pyx":71 */
  __pyx_v_taucs_out.m = __pyx_v_m;

  /* "/home/anand/pkgs/RandomRealizations/RandomRealizations/taucs_wrap.pyx":72 */
  __pyx_v_taucs_out.flags = __pyx_v_flags;

  /* "/home/anand/pkgs/RandomRealizations/RandomRealizations/taucs_wrap.pyx":73 */
  __pyx_v_taucs_out.colptr = __pyx_v_colptr;

  /* "/home/anand/pkgs/RandomRealizations/RandomRealizations/taucs_wrap.pyx":74 */
  __pyx_v_taucs_out.rowind = __pyx_v_rowind;

  /* "/home/anand/pkgs/RandomRealizations/RandomRealizations/taucs_wrap.pyx":75 */
  __pyx_v_taucs_out.values.d = __pyx_v_values;

  /* "/home/anand/pkgs/RandomRealizations/RandomRealizations/taucs_wrap.pyx":78 */
  __pyx_r = (&__pyx_v_taucs_out);
  goto __pyx_L0;

  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("taucs_wrap.scipy_to_taucs");
  __pyx_L0:;
  Py_DECREF(__pyx_v_CSC);
  return __pyx_r;
}

static PyObject *__pyx_n_zeros;
static PyObject *__pyx_n_float;
static PyObject *__pyx_n_dtype;
static PyObject *__pyx_n_int;


static PyObject *__pyx_f_10taucs_wrap_taucs_to_scipy(taucs_ccs_matrix (*__pyx_v_taucs_in_ptr)) {
  PyObject *__pyx_v_sparse_out;
  PyObject *__pyx_v_data;
  PyObject *__pyx_v_indptr;
  PyObject *__pyx_v_indices;
  taucs_ccs_matrix __pyx_v_taucs_in;
  int __pyx_v_npts;
  int __pyx_v_np1;
  int __pyx_v_i;
  double (*__pyx_v_values_in);
  int (*__pyx_v_colptr_in);
  int (*__pyx_v_rowind_in);
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  __pyx_v_sparse_out = Py_None; Py_INCREF(Py_None);
  __pyx_v_data = Py_None; Py_INCREF(Py_None);
  __pyx_v_indptr = Py_None; Py_INCREF(Py_None);
  __pyx_v_indices = Py_None; Py_INCREF(Py_None);

  /* "/home/anand/pkgs/RandomRealizations/RandomRealizations/taucs_wrap.pyx":95 */
  __pyx_v_taucs_in = (__pyx_v_taucs_in_ptr[0]);

  /* "/home/anand/pkgs/RandomRealizations/RandomRealizations/taucs_wrap.pyx":98 */
  __pyx_v_values_in = __pyx_v_taucs_in.values.d;

  /* "/home/anand/pkgs/RandomRealizations/RandomRealizations/taucs_wrap.pyx":99 */
  __pyx_v_colptr_in = __pyx_v_taucs_in.colptr;

  /* "/home/anand/pkgs/RandomRealizations/RandomRealizations/taucs_wrap.pyx":100 */
  __pyx_v_rowind_in = __pyx_v_taucs_in.rowind;

  /* "/home/anand/pkgs/RandomRealizations/RandomRealizations/taucs_wrap.pyx":103 */
  __pyx_v_np1 = (__pyx_v_taucs_in.n + 1);

  /* "/home/anand/pkgs/RandomRealizations/RandomRealizations/taucs_wrap.pyx":106 */
  __pyx_v_npts = (__pyx_v_taucs_in.colptr[__pyx_v_taucs_in.n]);

  /* "/home/anand/pkgs/RandomRealizations/RandomRealizations/taucs_wrap.pyx":109 */
  __pyx_1 = __Pyx_GetName(__pyx_m, __pyx_n_np); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 109; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_zeros); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 109; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyInt_FromLong(__pyx_v_npts); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 109; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 109; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_1);
  __pyx_1 = 0;
  __pyx_1 = PyDict_New(); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 109; goto __pyx_L1;}
  __pyx_4 = __Pyx_GetName(__pyx_b, __pyx_n_float); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 109; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_1, __pyx_n_dtype, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 109; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_4 = PyEval_CallObjectWithKeywords(__pyx_2, __pyx_3, __pyx_1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 109; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_v_data);
  __pyx_v_data = __pyx_4;
  __pyx_4 = 0;

  /* "/home/anand/pkgs/RandomRealizations/RandomRealizations/taucs_wrap.pyx":110 */
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_np); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 110; goto __pyx_L1;}
  __pyx_3 = PyObject_GetAttr(__pyx_2, __pyx_n_zeros); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 110; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_1 = PyInt_FromLong(__pyx_v_npts); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 110; goto __pyx_L1;}
  __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 110; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_1);
  __pyx_1 = 0;
  __pyx_2 = PyDict_New(); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 110; goto __pyx_L1;}
  __pyx_1 = __Pyx_GetName(__pyx_b, __pyx_n_int); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 110; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_2, __pyx_n_dtype, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 110; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyEval_CallObjectWithKeywords(__pyx_3, __pyx_4, __pyx_2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 110; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_v_indices);
  __pyx_v_indices = __pyx_1;
  __pyx_1 = 0;

  /* "/home/anand/pkgs/RandomRealizations/RandomRealizations/taucs_wrap.pyx":111 */
  __pyx_3 = __Pyx_GetName(__pyx_m, __pyx_n_np); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 111; goto __pyx_L1;}
  __pyx_4 = PyObject_GetAttr(__pyx_3, __pyx_n_zeros); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 111; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_2 = PyInt_FromLong(__pyx_v_np1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 111; goto __pyx_L1;}
  __pyx_1 = PyTuple_New(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 111; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_2);
  __pyx_2 = 0;
  __pyx_3 = PyDict_New(); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 111; goto __pyx_L1;}
  __pyx_2 = __Pyx_GetName(__pyx_b, __pyx_n_int); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 111; goto __pyx_L1;}
  if (PyDict_SetItem(__pyx_3, __pyx_n_dtype, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 111; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_2 = PyEval_CallObjectWithKeywords(__pyx_4, __pyx_1, __pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 111; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_v_indptr);
  __pyx_v_indptr = __pyx_2;
  __pyx_2 = 0;

  /* "/home/anand/pkgs/RandomRealizations/RandomRealizations/taucs_wrap.pyx":114 */
  for (__pyx_v_i = 0; __pyx_v_i < __pyx_v_npts; ++__pyx_v_i) {

    /* "/home/anand/pkgs/RandomRealizations/RandomRealizations/taucs_wrap.pyx":115 */
    __pyx_4 = PyFloat_FromDouble((__pyx_v_values_in[__pyx_v_i])); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; goto __pyx_L1;}
    __pyx_1 = PyInt_FromLong(__pyx_v_i); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; goto __pyx_L1;}
    if (PyObject_SetItem(__pyx_v_data, __pyx_1, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    Py_DECREF(__pyx_4); __pyx_4 = 0;

    /* "/home/anand/pkgs/RandomRealizations/RandomRealizations/taucs_wrap.pyx":116 */
    __pyx_3 = PyInt_FromLong((__pyx_v_rowind_in[__pyx_v_i])); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 116; goto __pyx_L1;}
    __pyx_2 = PyInt_FromLong(__pyx_v_i); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 116; goto __pyx_L1;}
    if (PyObject_SetItem(__pyx_v_indices, __pyx_2, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 116; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_L2:;
  }
  __pyx_L3:;

  /* "/home/anand/pkgs/RandomRealizations/RandomRealizations/taucs_wrap.pyx":118 */
  for (__pyx_v_i = 0; __pyx_v_i < __pyx_v_np1; ++__pyx_v_i) {

    /* "/home/anand/pkgs/RandomRealizations/RandomRealizations/taucs_wrap.pyx":119 */
    __pyx_1 = PyInt_FromLong((__pyx_v_colptr_in[__pyx_v_i])); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 119; goto __pyx_L1;}
    __pyx_4 = PyInt_FromLong(__pyx_v_i); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 119; goto __pyx_L1;}
    if (PyObject_SetItem(__pyx_v_indptr, __pyx_4, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 119; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_L4:;
  }
  __pyx_L5:;

  /* "/home/anand/pkgs/RandomRealizations/RandomRealizations/taucs_wrap.pyx":122 */
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_n_csc_matrix); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 122; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(3); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 122; goto __pyx_L1;}
  Py_INCREF(__pyx_v_data);
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_v_data);
  Py_INCREF(__pyx_v_indices);
  PyTuple_SET_ITEM(__pyx_3, 1, __pyx_v_indices);
  Py_INCREF(__pyx_v_indptr);
  PyTuple_SET_ITEM(__pyx_3, 2, __pyx_v_indptr);
  __pyx_4 = PyTuple_New(1); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 122; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_3);
  __pyx_3 = 0;
  __pyx_1 = PyObject_CallObject(__pyx_2, __pyx_4); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 122; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  Py_DECREF(__pyx_v_sparse_out);
  __pyx_v_sparse_out = __pyx_1;
  __pyx_1 = 0;

  /* "/home/anand/pkgs/RandomRealizations/RandomRealizations/taucs_wrap.pyx":124 */
  Py_INCREF(__pyx_v_sparse_out);
  __pyx_r = __pyx_v_sparse_out;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("taucs_wrap.taucs_to_scipy");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_sparse_out);
  Py_DECREF(__pyx_v_data);
  Py_DECREF(__pyx_v_indptr);
  Py_DECREF(__pyx_v_indices);
  return __pyx_r;
}

static char (__pyx_k13[]) = "S";

static PyObject *__pyx_f_10taucs_wrap_taucs_factor(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_10taucs_wrap_taucs_factor(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_scipy_matrix = 0;
  PyObject *__pyx_v_uplo = 0;
  taucs_ccs_matrix (*__pyx_v_taucs_matrix);
  taucs_ccs_matrix (*__pyx_v_factored_taucs_matrix);
  void (*__pyx_v_opaque_factor);
  PyObject *__pyx_r;
  char (*__pyx_1);
  taucs_ccs_matrix (*__pyx_2);
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {"scipy_matrix","uplo",0};
  __pyx_v_uplo = __pyx_k5;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O|O", __pyx_argnames, &__pyx_v_scipy_matrix, &__pyx_v_uplo)) return 0;
  Py_INCREF(__pyx_v_scipy_matrix);
  Py_INCREF(__pyx_v_uplo);

  /* "/home/anand/pkgs/RandomRealizations/RandomRealizations/taucs_wrap.pyx":132 */
  __pyx_1 = PyString_AsString(__pyx_v_uplo); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 132; goto __pyx_L1;}
  __pyx_2 = __pyx_f_10taucs_wrap_scipy_to_taucs(__pyx_v_scipy_matrix,__pyx_k13,__pyx_1,TAUCS_DOUBLE); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 132; goto __pyx_L1;}
  __pyx_v_taucs_matrix = __pyx_2;

  /* "/home/anand/pkgs/RandomRealizations/RandomRealizations/taucs_wrap.pyx":133 */
  __pyx_v_opaque_factor = taucs_ccs_factor_llt_mf(__pyx_v_taucs_matrix);

  /* "/home/anand/pkgs/RandomRealizations/RandomRealizations/taucs_wrap.pyx":134 */
  __pyx_v_factored_taucs_matrix = taucs_supernodal_factor_to_ccs(__pyx_v_opaque_factor);

  /* "/home/anand/pkgs/RandomRealizations/RandomRealizations/taucs_wrap.pyx":136 */
  __pyx_3 = __pyx_f_10taucs_wrap_taucs_to_scipy(__pyx_v_taucs_matrix); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 136; goto __pyx_L1;}
  __pyx_r = __pyx_3;
  __pyx_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("taucs_wrap.taucs_factor");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_scipy_matrix);
  Py_DECREF(__pyx_v_uplo);
  return __pyx_r;
}

static __Pyx_InternTabEntry __pyx_intern_tab[] = {
  {&__pyx_n_U, "U"},
  {&__pyx_n_csc_matrix, "csc_matrix"},
  {&__pyx_n_data, "data"},
  {&__pyx_n_dtype, "dtype"},
  {&__pyx_n_float, "float"},
  {&__pyx_n_indices, "indices"},
  {&__pyx_n_indptr, "indptr"},
  {&__pyx_n_int, "int"},
  {&__pyx_n_np, "np"},
  {&__pyx_n_numpy, "numpy"},
  {&__pyx_n_shape, "shape"},
  {&__pyx_n_taucs_factor, "taucs_factor"},
  {&__pyx_n_zeros, "zeros"},
  {0, 0}
};

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_k1p, __pyx_k1, sizeof(__pyx_k1)},
  {0, 0, 0}
};

static struct PyMethodDef __pyx_methods[] = {
  {"taucs_factor", (PyCFunction)__pyx_f_10taucs_wrap_taucs_factor, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC inittaucs_wrap(void); /*proto*/
PyMODINIT_FUNC inittaucs_wrap(void) {
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  __pyx_init_filenames();
  __pyx_m = Py_InitModule4("taucs_wrap", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (__Pyx_InternStrings(__pyx_intern_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};

  /* "/home/anand/pkgs/RandomRealizations/RandomRealizations/taucs_wrap.pyx":1 */
  __pyx_1 = PyList_New(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;}
  Py_INCREF(__pyx_n_csc_matrix);
  PyList_SET_ITEM(__pyx_1, 0, __pyx_n_csc_matrix);
  __pyx_2 = __Pyx_Import(__pyx_k1p, __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyObject_GetAttr(__pyx_2, __pyx_n_csc_matrix); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_csc_matrix, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/anand/pkgs/RandomRealizations/RandomRealizations/taucs_wrap.pyx":2 */
  __pyx_2 = __Pyx_Import(__pyx_n_numpy, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_np, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/anand/pkgs/RandomRealizations/RandomRealizations/taucs_wrap.pyx":127 */
  Py_INCREF(__pyx_n_U);
  __pyx_k5 = __pyx_n_U;
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("taucs_wrap");
}

static char *__pyx_filenames[] = {
  "taucs_wrap.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list) {
    PyObject *__import__ = 0;
    PyObject *empty_list = 0;
    PyObject *module = 0;
    PyObject *global_dict = 0;
    PyObject *empty_dict = 0;
    PyObject *list;
    __import__ = PyObject_GetAttrString(__pyx_b, "__import__");
    if (!__import__)
        goto bad;
    if (from_list)
        list = from_list;
    else {
        empty_list = PyList_New(0);
        if (!empty_list)
            goto bad;
        list = empty_list;
    }
    global_dict = PyModule_GetDict(__pyx_m);
    if (!global_dict)
        goto bad;
    empty_dict = PyDict_New();
    if (!empty_dict)
        goto bad;
    module = PyObject_CallFunction(__import__, "OOOO",
        name, global_dict, empty_dict, list);
bad:
    Py_XDECREF(empty_list);
    Py_XDECREF(__import__);
    Py_XDECREF(empty_dict);
    return module;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t) {
    while (t->p) {
        *t->p = PyString_InternFromString(t->s);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
