# "test" conda envs are used to set up our CI environment in GitHub actions
name: pymc-test
channels:
- conda-forge
- defaults
dependencies:
# Base dependencies (see install guide for Windows)
- arviz>=0.13.0
- blas
- cachetools>=4.2.1
- cloudpickle
- h5py>=2.7
- libpython
- mkl-service>=2.3.0
- m2w64-toolchain
- numpy>=1.25.0
- pandas>=0.24.0
- pip
- pytensor>=2.26.2,<2.27
- python-graphviz
- networkx
- rich>=13.7.1
- scipy>=1.4.1
- typing-extensions>=3.7.4
- threadpoolctl>=3.1.0
# Extra dependencies for testing
- ipython>=7.16
- pre-commit>=2.8.0
- pytest-cov>=2.5
- pytest>=3.0
- mypy=1.5.1
- types-cachetools
- pip:
  - numdifftools>=0.9.40
  - mcbackend>=0.4.0
