/* Generated by Pyrex 0.9.8.5 on Fri May 22 14:21:36 2009 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)	PyInt_AsLong(o)
#endif
#if !defined(WIN32) && !defined(MS_WINDOWS)
  #ifndef __stdcall
    #define __stdcall
  #endif
  #ifndef __cdecl
    #define __cdecl
  #endif
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>
#include "numpy/ndarrayobject.h"


typedef struct {PyObject **p; int i; char *s; long n;} __Pyx_StringTabEntry; /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
static char **__pyx_f;

static int __Pyx_SetItemInt(PyObject *o, Py_ssize_t i, PyObject *v); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/

static void __Pyx_AddTraceback(char *funcname); /*proto*/

/* Declarations from pymc.Container_values */


/* Declarations from implementation of pymc.Container_values */

struct __pyx_obj_4pymc_16Container_values_LCValue {
  PyObject_HEAD
  void **nonval_obj;
  int *val_ind;
  int *nonval_ind;
  PyObject *_value;
  PyObject *val_obj;
  int n_val;
  int n_nonval;
};

struct __pyx_obj_4pymc_16Container_values_DCValue {
  PyObject_HEAD
  void **val_keys;
  void **nonval_obj;
  void **nonval_keys;
  PyObject *_value;
  PyObject *val_obj;
  int n_val;
  int n_nonval;
};

struct __pyx_obj_4pymc_16Container_values_OCValue {
  PyObject_HEAD
  void **val_keys;
  void **nonval_obj;
  void **nonval_keys;
  PyObject *_value;
  PyObject *val_obj;
  int n_val;
  int n_nonval;
};

struct __pyx_obj_4pymc_16Container_values_ACValue {
  PyObject_HEAD
  void **nonval_obj;
  int *val_ind;
  int *nonval_ind;
  PyObject *_ravelledvalue;
  PyObject *val_obj;
  int n_val;
  int n_nonval;
};





static PyTypeObject *__pyx_ptype_4pymc_16Container_values_LCValue = 0;
static PyTypeObject *__pyx_ptype_4pymc_16Container_values_DCValue = 0;
static PyTypeObject *__pyx_ptype_4pymc_16Container_values_OCValue = 0;
static PyTypeObject *__pyx_ptype_4pymc_16Container_values_ACValue = 0;

static char __pyx_k1[] = "_value";
static char __pyx_k2[] = "val_ind";
static char __pyx_k3[] = "val_obj";
static char __pyx_k4[] = "n_val";
static char __pyx_k5[] = "nonval_ind";
static char __pyx_k6[] = "nonval_obj";
static char __pyx_k7[] = "n_nonval";
static char __pyx_k8[] = "value";
static char __pyx_k9[] = "val_keys";
static char __pyx_k10[] = "nonval_keys";
static char __pyx_k11[] = "__dict__";
static char __pyx_k12[] = "_dict_container";
static char __pyx_k13[] = "_ravelledvalue";
static char __pyx_k14[] = "Node";
static char __pyx_k15[] = "Variable";
static char __pyx_k16[] = "ContainerBase";
static char __pyx_k17[] = "copy";
static char __pyx_k18[] = "numpy";
static char __pyx_k19[] = "ndarray";
static char __pyx_k20[] = "array";
static char __pyx_k21[] = "zeros";
static char __pyx_k22[] = "shape";
static char __pyx_k23[] = "arange";
static char __pyx_k24[] = "where";

static PyObject *__pyx_n_ContainerBase;
static PyObject *__pyx_n_Node;
static PyObject *__pyx_n_Variable;
static PyObject *__pyx_n___dict__;
static PyObject *__pyx_n__dict_container;
static PyObject *__pyx_n__ravelledvalue;
static PyObject *__pyx_n__value;
static PyObject *__pyx_n_arange;
static PyObject *__pyx_n_array;
static PyObject *__pyx_n_copy;
static PyObject *__pyx_n_n_nonval;
static PyObject *__pyx_n_n_val;
static PyObject *__pyx_n_ndarray;
static PyObject *__pyx_n_nonval_ind;
static PyObject *__pyx_n_nonval_keys;
static PyObject *__pyx_n_nonval_obj;
static PyObject *__pyx_n_numpy;
static PyObject *__pyx_n_shape;
static PyObject *__pyx_n_val_ind;
static PyObject *__pyx_n_val_keys;
static PyObject *__pyx_n_val_obj;
static PyObject *__pyx_n_value;
static PyObject *__pyx_n_where;
static PyObject *__pyx_n_zeros;


static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_n_ContainerBase, 1, __pyx_k16, sizeof(__pyx_k16)},
  {&__pyx_n_Node, 1, __pyx_k14, sizeof(__pyx_k14)},
  {&__pyx_n_Variable, 1, __pyx_k15, sizeof(__pyx_k15)},
  {&__pyx_n___dict__, 1, __pyx_k11, sizeof(__pyx_k11)},
  {&__pyx_n__dict_container, 1, __pyx_k12, sizeof(__pyx_k12)},
  {&__pyx_n__ravelledvalue, 1, __pyx_k13, sizeof(__pyx_k13)},
  {&__pyx_n__value, 1, __pyx_k1, sizeof(__pyx_k1)},
  {&__pyx_n_arange, 1, __pyx_k23, sizeof(__pyx_k23)},
  {&__pyx_n_array, 1, __pyx_k20, sizeof(__pyx_k20)},
  {&__pyx_n_copy, 1, __pyx_k17, sizeof(__pyx_k17)},
  {&__pyx_n_n_nonval, 1, __pyx_k7, sizeof(__pyx_k7)},
  {&__pyx_n_n_val, 1, __pyx_k4, sizeof(__pyx_k4)},
  {&__pyx_n_ndarray, 1, __pyx_k19, sizeof(__pyx_k19)},
  {&__pyx_n_nonval_ind, 1, __pyx_k5, sizeof(__pyx_k5)},
  {&__pyx_n_nonval_keys, 1, __pyx_k10, sizeof(__pyx_k10)},
  {&__pyx_n_nonval_obj, 1, __pyx_k6, sizeof(__pyx_k6)},
  {&__pyx_n_numpy, 1, __pyx_k18, sizeof(__pyx_k18)},
  {&__pyx_n_shape, 1, __pyx_k22, sizeof(__pyx_k22)},
  {&__pyx_n_val_ind, 1, __pyx_k2, sizeof(__pyx_k2)},
  {&__pyx_n_val_keys, 1, __pyx_k9, sizeof(__pyx_k9)},
  {&__pyx_n_val_obj, 1, __pyx_k3, sizeof(__pyx_k3)},
  {&__pyx_n_value, 1, __pyx_k8, sizeof(__pyx_k8)},
  {&__pyx_n_where, 1, __pyx_k24, sizeof(__pyx_k24)},
  {&__pyx_n_zeros, 1, __pyx_k21, sizeof(__pyx_k21)},
  {0, 0, 0, 0}
};



/* Implementation of pymc.Container_values */

static int __pyx_f_4pymc_16Container_values_7LCValue___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_4pymc_16Container_values_7LCValue___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_container = 0;
  int __pyx_r;
  PyObject *__pyx_1 = 0;
  int __pyx_2;
  static char *__pyx_argnames[] = {"container",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_container)) return -1;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_container);

  /* "/Users/anand/renearch/pymc-git/pymc/Container_values.pyx":26 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_container, __pyx_n__value); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 26; goto __pyx_L1;}
  Py_DECREF(((struct __pyx_obj_4pymc_16Container_values_LCValue *)__pyx_v_self)->_value);
  ((struct __pyx_obj_4pymc_16Container_values_LCValue *)__pyx_v_self)->_value = __pyx_1;
  __pyx_1 = 0;

  /* "/Users/anand/renearch/pymc-git/pymc/Container_values.pyx":27 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_container, __pyx_n_val_ind); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 27; goto __pyx_L1;}
  ((struct __pyx_obj_4pymc_16Container_values_LCValue *)__pyx_v_self)->val_ind = ((int *)PyArray_DATA(__pyx_1));
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Users/anand/renearch/pymc-git/pymc/Container_values.pyx":28 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_container, __pyx_n_val_obj); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 28; goto __pyx_L1;}
  Py_DECREF(((struct __pyx_obj_4pymc_16Container_values_LCValue *)__pyx_v_self)->val_obj);
  ((struct __pyx_obj_4pymc_16Container_values_LCValue *)__pyx_v_self)->val_obj = __pyx_1;
  __pyx_1 = 0;

  /* "/Users/anand/renearch/pymc-git/pymc/Container_values.pyx":29 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_container, __pyx_n_n_val); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 29; goto __pyx_L1;}
  __pyx_2 = PyInt_AsLong(__pyx_1); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 29; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  ((struct __pyx_obj_4pymc_16Container_values_LCValue *)__pyx_v_self)->n_val = __pyx_2;

  /* "/Users/anand/renearch/pymc-git/pymc/Container_values.pyx":30 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_container, __pyx_n_nonval_ind); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 30; goto __pyx_L1;}
  ((struct __pyx_obj_4pymc_16Container_values_LCValue *)__pyx_v_self)->nonval_ind = ((int *)PyArray_DATA(__pyx_1));
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Users/anand/renearch/pymc-git/pymc/Container_values.pyx":31 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_container, __pyx_n_nonval_obj); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 31; goto __pyx_L1;}
  ((struct __pyx_obj_4pymc_16Container_values_LCValue *)__pyx_v_self)->nonval_obj = ((void **)PyArray_DATA(__pyx_1));
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Users/anand/renearch/pymc-git/pymc/Container_values.pyx":32 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_container, __pyx_n_n_nonval); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; goto __pyx_L1;}
  __pyx_2 = PyInt_AsLong(__pyx_1); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  ((struct __pyx_obj_4pymc_16Container_values_LCValue *)__pyx_v_self)->n_nonval = __pyx_2;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("pymc.Container_values.LCValue.__init__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_container);
  return __pyx_r;
}

static PyObject *__pyx_f_4pymc_16Container_values_7LCValue_run(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_4pymc_16Container_values_7LCValue_run(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_v_i;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/Users/anand/renearch/pymc-git/pymc/Container_values.pyx":36 */
  __pyx_1 = ((struct __pyx_obj_4pymc_16Container_values_LCValue *)__pyx_v_self)->n_val;
  for (__pyx_v_i = 0; __pyx_v_i < __pyx_1; ++__pyx_v_i) {
    __pyx_2 = PyObject_GetAttr(((PyObject *)PyList_GetItem(((struct __pyx_obj_4pymc_16Container_values_LCValue *)__pyx_v_self)->val_obj,__pyx_v_i)), __pyx_n_value); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 37; goto __pyx_L1;}
    if (__Pyx_SetItemInt(((struct __pyx_obj_4pymc_16Container_values_LCValue *)__pyx_v_self)->_value, (((struct __pyx_obj_4pymc_16Container_values_LCValue *)__pyx_v_self)->val_ind[__pyx_v_i]), __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 37; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
  }

  /* "/Users/anand/renearch/pymc-git/pymc/Container_values.pyx":38 */
  __pyx_1 = ((struct __pyx_obj_4pymc_16Container_values_LCValue *)__pyx_v_self)->n_nonval;
  for (__pyx_v_i = 0; __pyx_v_i < __pyx_1; ++__pyx_v_i) {
    if (__Pyx_SetItemInt(((struct __pyx_obj_4pymc_16Container_values_LCValue *)__pyx_v_self)->_value, (((struct __pyx_obj_4pymc_16Container_values_LCValue *)__pyx_v_self)->nonval_ind[__pyx_v_i]), ((PyObject *)(((struct __pyx_obj_4pymc_16Container_values_LCValue *)__pyx_v_self)->nonval_obj[__pyx_v_i]))) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 39; goto __pyx_L1;}
  }

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("pymc.Container_values.LCValue.run");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static int __pyx_f_4pymc_16Container_values_7DCValue___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_4pymc_16Container_values_7DCValue___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_container = 0;
  int __pyx_r;
  PyObject *__pyx_1 = 0;
  int __pyx_2;
  static char *__pyx_argnames[] = {"container",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_container)) return -1;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_container);

  /* "/Users/anand/renearch/pymc-git/pymc/Container_values.pyx":54 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_container, __pyx_n__value); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; goto __pyx_L1;}
  Py_DECREF(((struct __pyx_obj_4pymc_16Container_values_DCValue *)__pyx_v_self)->_value);
  ((struct __pyx_obj_4pymc_16Container_values_DCValue *)__pyx_v_self)->_value = __pyx_1;
  __pyx_1 = 0;

  /* "/Users/anand/renearch/pymc-git/pymc/Container_values.pyx":55 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_container, __pyx_n_val_keys); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 55; goto __pyx_L1;}
  ((struct __pyx_obj_4pymc_16Container_values_DCValue *)__pyx_v_self)->val_keys = ((void **)PyArray_DATA(__pyx_1));
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Users/anand/renearch/pymc-git/pymc/Container_values.pyx":57 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_container, __pyx_n_val_obj); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; goto __pyx_L1;}
  Py_DECREF(((struct __pyx_obj_4pymc_16Container_values_DCValue *)__pyx_v_self)->val_obj);
  ((struct __pyx_obj_4pymc_16Container_values_DCValue *)__pyx_v_self)->val_obj = __pyx_1;
  __pyx_1 = 0;

  /* "/Users/anand/renearch/pymc-git/pymc/Container_values.pyx":58 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_container, __pyx_n_n_val); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
  __pyx_2 = PyInt_AsLong(__pyx_1); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  ((struct __pyx_obj_4pymc_16Container_values_DCValue *)__pyx_v_self)->n_val = __pyx_2;

  /* "/Users/anand/renearch/pymc-git/pymc/Container_values.pyx":59 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_container, __pyx_n_nonval_keys); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 59; goto __pyx_L1;}
  ((struct __pyx_obj_4pymc_16Container_values_DCValue *)__pyx_v_self)->nonval_keys = ((void **)PyArray_DATA(__pyx_1));
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Users/anand/renearch/pymc-git/pymc/Container_values.pyx":60 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_container, __pyx_n_nonval_obj); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 60; goto __pyx_L1;}
  ((struct __pyx_obj_4pymc_16Container_values_DCValue *)__pyx_v_self)->nonval_obj = ((void **)PyArray_DATA(__pyx_1));
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Users/anand/renearch/pymc-git/pymc/Container_values.pyx":61 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_container, __pyx_n_n_nonval); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; goto __pyx_L1;}
  __pyx_2 = PyInt_AsLong(__pyx_1); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  ((struct __pyx_obj_4pymc_16Container_values_DCValue *)__pyx_v_self)->n_nonval = __pyx_2;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("pymc.Container_values.DCValue.__init__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_container);
  return __pyx_r;
}

static PyObject *__pyx_f_4pymc_16Container_values_7DCValue_run(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_4pymc_16Container_values_7DCValue_run(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_v_i;
  PyObject *__pyx_v_key;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_v_key = Py_None; Py_INCREF(Py_None);

  /* "/Users/anand/renearch/pymc-git/pymc/Container_values.pyx":66 */
  __pyx_1 = ((struct __pyx_obj_4pymc_16Container_values_DCValue *)__pyx_v_self)->n_val;
  for (__pyx_v_i = 0; __pyx_v_i < __pyx_1; ++__pyx_v_i) {

    /* "/Users/anand/renearch/pymc-git/pymc/Container_values.pyx":67 */
    Py_INCREF(((PyObject *)(((struct __pyx_obj_4pymc_16Container_values_DCValue *)__pyx_v_self)->val_keys[__pyx_v_i])));
    Py_DECREF(__pyx_v_key);
    __pyx_v_key = ((PyObject *)(((struct __pyx_obj_4pymc_16Container_values_DCValue *)__pyx_v_self)->val_keys[__pyx_v_i]));

    /* "/Users/anand/renearch/pymc-git/pymc/Container_values.pyx":68 */
    __pyx_2 = PyObject_GetAttr(((PyObject *)PyList_GetItem(((struct __pyx_obj_4pymc_16Container_values_DCValue *)__pyx_v_self)->val_obj,__pyx_v_i)), __pyx_n_value); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; goto __pyx_L1;}
    if (PyObject_SetItem(((struct __pyx_obj_4pymc_16Container_values_DCValue *)__pyx_v_self)->_value, __pyx_v_key, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
  }

  /* "/Users/anand/renearch/pymc-git/pymc/Container_values.pyx":69 */
  __pyx_1 = ((struct __pyx_obj_4pymc_16Container_values_DCValue *)__pyx_v_self)->n_nonval;
  for (__pyx_v_i = 0; __pyx_v_i < __pyx_1; ++__pyx_v_i) {

    /* "/Users/anand/renearch/pymc-git/pymc/Container_values.pyx":70 */
    Py_INCREF(((PyObject *)(((struct __pyx_obj_4pymc_16Container_values_DCValue *)__pyx_v_self)->nonval_keys[__pyx_v_i])));
    Py_DECREF(__pyx_v_key);
    __pyx_v_key = ((PyObject *)(((struct __pyx_obj_4pymc_16Container_values_DCValue *)__pyx_v_self)->nonval_keys[__pyx_v_i]));

    /* "/Users/anand/renearch/pymc-git/pymc/Container_values.pyx":71 */
    if (PyObject_SetItem(((struct __pyx_obj_4pymc_16Container_values_DCValue *)__pyx_v_self)->_value, __pyx_v_key, ((PyObject *)(((struct __pyx_obj_4pymc_16Container_values_DCValue *)__pyx_v_self)->nonval_obj[__pyx_v_i]))) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 71; goto __pyx_L1;}
  }

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("pymc.Container_values.DCValue.run");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_key);
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static int __pyx_f_4pymc_16Container_values_7OCValue___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_4pymc_16Container_values_7OCValue___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_container = 0;
  int __pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  int __pyx_3;
  static char *__pyx_argnames[] = {"container",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_container)) return -1;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_container);

  /* "/Users/anand/renearch/pymc-git/pymc/Container_values.pyx":84 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_container, __pyx_n__value); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 84; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n___dict__); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 84; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(((struct __pyx_obj_4pymc_16Container_values_OCValue *)__pyx_v_self)->_value);
  ((struct __pyx_obj_4pymc_16Container_values_OCValue *)__pyx_v_self)->_value = __pyx_2;
  __pyx_2 = 0;

  /* "/Users/anand/renearch/pymc-git/pymc/Container_values.pyx":85 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_container, __pyx_n__dict_container); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 85; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_val_keys); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 85; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  ((struct __pyx_obj_4pymc_16Container_values_OCValue *)__pyx_v_self)->val_keys = ((void **)PyArray_DATA(__pyx_2));
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/Users/anand/renearch/pymc-git/pymc/Container_values.pyx":86 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_container, __pyx_n__dict_container); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 86; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_val_obj); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 86; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(((struct __pyx_obj_4pymc_16Container_values_OCValue *)__pyx_v_self)->val_obj);
  ((struct __pyx_obj_4pymc_16Container_values_OCValue *)__pyx_v_self)->val_obj = __pyx_2;
  __pyx_2 = 0;

  /* "/Users/anand/renearch/pymc-git/pymc/Container_values.pyx":87 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_container, __pyx_n__dict_container); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 87; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_n_val); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 87; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_3 = PyInt_AsLong(__pyx_2); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 87; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  ((struct __pyx_obj_4pymc_16Container_values_OCValue *)__pyx_v_self)->n_val = __pyx_3;

  /* "/Users/anand/renearch/pymc-git/pymc/Container_values.pyx":88 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_container, __pyx_n__dict_container); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 88; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_nonval_keys); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 88; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  ((struct __pyx_obj_4pymc_16Container_values_OCValue *)__pyx_v_self)->nonval_keys = ((void **)PyArray_DATA(__pyx_2));
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/Users/anand/renearch/pymc-git/pymc/Container_values.pyx":89 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_container, __pyx_n__dict_container); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 89; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_nonval_obj); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 89; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  ((struct __pyx_obj_4pymc_16Container_values_OCValue *)__pyx_v_self)->nonval_obj = ((void **)PyArray_DATA(__pyx_2));
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/Users/anand/renearch/pymc-git/pymc/Container_values.pyx":90 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_container, __pyx_n__dict_container); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 90; goto __pyx_L1;}
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_n_nonval); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 90; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_3 = PyInt_AsLong(__pyx_2); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 90; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  ((struct __pyx_obj_4pymc_16Container_values_OCValue *)__pyx_v_self)->n_nonval = __pyx_3;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("pymc.Container_values.OCValue.__init__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_container);
  return __pyx_r;
}

static PyObject *__pyx_f_4pymc_16Container_values_7OCValue_run(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_4pymc_16Container_values_7OCValue_run(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_v_i;
  PyObject *__pyx_v_key;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);
  __pyx_v_key = Py_None; Py_INCREF(Py_None);

  /* "/Users/anand/renearch/pymc-git/pymc/Container_values.pyx":94 */
  __pyx_1 = ((struct __pyx_obj_4pymc_16Container_values_OCValue *)__pyx_v_self)->n_val;
  for (__pyx_v_i = 0; __pyx_v_i < __pyx_1; ++__pyx_v_i) {

    /* "/Users/anand/renearch/pymc-git/pymc/Container_values.pyx":95 */
    Py_INCREF(((PyObject *)(((struct __pyx_obj_4pymc_16Container_values_OCValue *)__pyx_v_self)->val_keys[__pyx_v_i])));
    Py_DECREF(__pyx_v_key);
    __pyx_v_key = ((PyObject *)(((struct __pyx_obj_4pymc_16Container_values_OCValue *)__pyx_v_self)->val_keys[__pyx_v_i]));

    /* "/Users/anand/renearch/pymc-git/pymc/Container_values.pyx":96 */
    __pyx_2 = PyObject_GetAttr(((PyObject *)PyList_GetItem(((struct __pyx_obj_4pymc_16Container_values_OCValue *)__pyx_v_self)->val_obj,__pyx_v_i)), __pyx_n_value); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 96; goto __pyx_L1;}
    if (PyObject_SetItem(((struct __pyx_obj_4pymc_16Container_values_OCValue *)__pyx_v_self)->_value, __pyx_v_key, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 96; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
  }

  /* "/Users/anand/renearch/pymc-git/pymc/Container_values.pyx":97 */
  __pyx_1 = ((struct __pyx_obj_4pymc_16Container_values_OCValue *)__pyx_v_self)->n_nonval;
  for (__pyx_v_i = 0; __pyx_v_i < __pyx_1; ++__pyx_v_i) {

    /* "/Users/anand/renearch/pymc-git/pymc/Container_values.pyx":98 */
    Py_INCREF(((PyObject *)(((struct __pyx_obj_4pymc_16Container_values_OCValue *)__pyx_v_self)->nonval_keys[__pyx_v_i])));
    Py_DECREF(__pyx_v_key);
    __pyx_v_key = ((PyObject *)(((struct __pyx_obj_4pymc_16Container_values_OCValue *)__pyx_v_self)->nonval_keys[__pyx_v_i]));

    /* "/Users/anand/renearch/pymc-git/pymc/Container_values.pyx":99 */
    if (PyObject_SetItem(((struct __pyx_obj_4pymc_16Container_values_OCValue *)__pyx_v_self)->_value, __pyx_v_key, ((PyObject *)(((struct __pyx_obj_4pymc_16Container_values_OCValue *)__pyx_v_self)->nonval_obj[__pyx_v_i]))) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; goto __pyx_L1;}
  }

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("pymc.Container_values.OCValue.run");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_key);
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static int __pyx_f_4pymc_16Container_values_7ACValue___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_4pymc_16Container_values_7ACValue___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_container = 0;
  int __pyx_r;
  PyObject *__pyx_1 = 0;
  int __pyx_2;
  static char *__pyx_argnames[] = {"container",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_container)) return -1;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_container);

  /* "/Users/anand/renearch/pymc-git/pymc/Container_values.pyx":113 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_container, __pyx_n__ravelledvalue); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 113; goto __pyx_L1;}
  Py_DECREF(((struct __pyx_obj_4pymc_16Container_values_ACValue *)__pyx_v_self)->_ravelledvalue);
  ((struct __pyx_obj_4pymc_16Container_values_ACValue *)__pyx_v_self)->_ravelledvalue = __pyx_1;
  __pyx_1 = 0;

  /* "/Users/anand/renearch/pymc-git/pymc/Container_values.pyx":114 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_container, __pyx_n_val_ind); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 114; goto __pyx_L1;}
  ((struct __pyx_obj_4pymc_16Container_values_ACValue *)__pyx_v_self)->val_ind = ((int *)PyArray_DATA(__pyx_1));
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Users/anand/renearch/pymc-git/pymc/Container_values.pyx":115 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_container, __pyx_n_val_obj); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; goto __pyx_L1;}
  Py_DECREF(((struct __pyx_obj_4pymc_16Container_values_ACValue *)__pyx_v_self)->val_obj);
  ((struct __pyx_obj_4pymc_16Container_values_ACValue *)__pyx_v_self)->val_obj = __pyx_1;
  __pyx_1 = 0;

  /* "/Users/anand/renearch/pymc-git/pymc/Container_values.pyx":116 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_container, __pyx_n_n_val); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 116; goto __pyx_L1;}
  __pyx_2 = PyInt_AsLong(__pyx_1); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 116; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  ((struct __pyx_obj_4pymc_16Container_values_ACValue *)__pyx_v_self)->n_val = __pyx_2;

  /* "/Users/anand/renearch/pymc-git/pymc/Container_values.pyx":117 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_container, __pyx_n_nonval_ind); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 117; goto __pyx_L1;}
  ((struct __pyx_obj_4pymc_16Container_values_ACValue *)__pyx_v_self)->nonval_ind = ((int *)PyArray_DATA(__pyx_1));
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Users/anand/renearch/pymc-git/pymc/Container_values.pyx":118 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_container, __pyx_n_nonval_obj); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 118; goto __pyx_L1;}
  ((struct __pyx_obj_4pymc_16Container_values_ACValue *)__pyx_v_self)->nonval_obj = ((void **)PyArray_DATA(__pyx_1));
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Users/anand/renearch/pymc-git/pymc/Container_values.pyx":119 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_container, __pyx_n_n_nonval); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 119; goto __pyx_L1;}
  __pyx_2 = PyInt_AsLong(__pyx_1); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 119; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  ((struct __pyx_obj_4pymc_16Container_values_ACValue *)__pyx_v_self)->n_nonval = __pyx_2;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("pymc.Container_values.ACValue.__init__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_container);
  return __pyx_r;
}

static PyObject *__pyx_f_4pymc_16Container_values_7ACValue_run(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_4pymc_16Container_values_7ACValue_run(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_v_i;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "/Users/anand/renearch/pymc-git/pymc/Container_values.pyx":122 */
  __pyx_1 = ((struct __pyx_obj_4pymc_16Container_values_ACValue *)__pyx_v_self)->n_val;
  for (__pyx_v_i = 0; __pyx_v_i < __pyx_1; ++__pyx_v_i) {
    __pyx_2 = PyObject_GetAttr(((PyObject *)PyList_GetItem(((struct __pyx_obj_4pymc_16Container_values_ACValue *)__pyx_v_self)->val_obj,__pyx_v_i)), __pyx_n_value); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 123; goto __pyx_L1;}
    if (__Pyx_SetItemInt(((struct __pyx_obj_4pymc_16Container_values_ACValue *)__pyx_v_self)->_ravelledvalue, (((struct __pyx_obj_4pymc_16Container_values_ACValue *)__pyx_v_self)->val_ind[__pyx_v_i]), __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 123; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
  }

  /* "/Users/anand/renearch/pymc-git/pymc/Container_values.pyx":124 */
  __pyx_1 = ((struct __pyx_obj_4pymc_16Container_values_ACValue *)__pyx_v_self)->n_nonval;
  for (__pyx_v_i = 0; __pyx_v_i < __pyx_1; ++__pyx_v_i) {
    if (__Pyx_SetItemInt(((struct __pyx_obj_4pymc_16Container_values_ACValue *)__pyx_v_self)->_ravelledvalue, (((struct __pyx_obj_4pymc_16Container_values_ACValue *)__pyx_v_self)->nonval_ind[__pyx_v_i]), ((PyObject *)(((struct __pyx_obj_4pymc_16Container_values_ACValue *)__pyx_v_self)->nonval_obj[__pyx_v_i]))) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 125; goto __pyx_L1;}
  }

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("pymc.Container_values.ACValue.run");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_tp_new_4pymc_16Container_values_LCValue(PyTypeObject *t, PyObject *a, PyObject *k) {
  struct __pyx_obj_4pymc_16Container_values_LCValue *p;
  PyObject *o = (*t->tp_alloc)(t, 0);
  if (!o) return 0;
  p = ((struct __pyx_obj_4pymc_16Container_values_LCValue *)o);
  p->_value = Py_None; Py_INCREF(Py_None);
  p->val_obj = Py_None; Py_INCREF(Py_None);
  return o;
}

static void __pyx_tp_dealloc_4pymc_16Container_values_LCValue(PyObject *o) {
  struct __pyx_obj_4pymc_16Container_values_LCValue *p = (struct __pyx_obj_4pymc_16Container_values_LCValue *)o;
  Py_XDECREF(p->_value);
  Py_XDECREF(p->val_obj);
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_4pymc_16Container_values_LCValue(PyObject *o, visitproc v, void *a) {
  int e;
  struct __pyx_obj_4pymc_16Container_values_LCValue *p = (struct __pyx_obj_4pymc_16Container_values_LCValue *)o;
  if (p->_value) {
    e = (*v)(p->_value, a); if (e) return e;
  }
  if (p->val_obj) {
    e = (*v)(p->val_obj, a); if (e) return e;
  }
  return 0;
}

static int __pyx_tp_clear_4pymc_16Container_values_LCValue(PyObject *o) {
  struct __pyx_obj_4pymc_16Container_values_LCValue *p = (struct __pyx_obj_4pymc_16Container_values_LCValue *)o;
  PyObject *t;
  t = p->_value; 
  p->_value = Py_None; Py_INCREF(Py_None);
  Py_XDECREF(t);
  t = p->val_obj; 
  p->val_obj = Py_None; Py_INCREF(Py_None);
  Py_XDECREF(t);
  return 0;
}

static struct PyMethodDef __pyx_methods_4pymc_16Container_values_LCValue[] = {
  {"run", (PyCFunction)__pyx_f_4pymc_16Container_values_7LCValue_run, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_LCValue = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
  #if Py_TPFLAGS_DEFAULT & Py_TPFLAGS_HAVE_INDEX
  0, /*nb_index*/
  #endif
};

static PySequenceMethods __pyx_tp_as_sequence_LCValue = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_LCValue = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_LCValue = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_4pymc_16Container_values_LCValue = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "pymc.Container_values.LCValue", /*tp_name*/
  sizeof(struct __pyx_obj_4pymc_16Container_values_LCValue), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_4pymc_16Container_values_LCValue, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_LCValue, /*tp_as_number*/
  &__pyx_tp_as_sequence_LCValue, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_LCValue, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_LCValue, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE|Py_TPFLAGS_HAVE_GC, /*tp_flags*/
  "\n    l = LCValue(container)\n    l.run()\n\n    run() method fills in value of ListContainer.\n    ", /*tp_doc*/
  __pyx_tp_traverse_4pymc_16Container_values_LCValue, /*tp_traverse*/
  __pyx_tp_clear_4pymc_16Container_values_LCValue, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_4pymc_16Container_values_LCValue, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  __pyx_f_4pymc_16Container_values_7LCValue___init__, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_4pymc_16Container_values_LCValue, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static PyObject *__pyx_tp_new_4pymc_16Container_values_DCValue(PyTypeObject *t, PyObject *a, PyObject *k) {
  struct __pyx_obj_4pymc_16Container_values_DCValue *p;
  PyObject *o = (*t->tp_alloc)(t, 0);
  if (!o) return 0;
  p = ((struct __pyx_obj_4pymc_16Container_values_DCValue *)o);
  p->_value = Py_None; Py_INCREF(Py_None);
  p->val_obj = Py_None; Py_INCREF(Py_None);
  return o;
}

static void __pyx_tp_dealloc_4pymc_16Container_values_DCValue(PyObject *o) {
  struct __pyx_obj_4pymc_16Container_values_DCValue *p = (struct __pyx_obj_4pymc_16Container_values_DCValue *)o;
  Py_XDECREF(p->_value);
  Py_XDECREF(p->val_obj);
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_4pymc_16Container_values_DCValue(PyObject *o, visitproc v, void *a) {
  int e;
  struct __pyx_obj_4pymc_16Container_values_DCValue *p = (struct __pyx_obj_4pymc_16Container_values_DCValue *)o;
  if (p->_value) {
    e = (*v)(p->_value, a); if (e) return e;
  }
  if (p->val_obj) {
    e = (*v)(p->val_obj, a); if (e) return e;
  }
  return 0;
}

static int __pyx_tp_clear_4pymc_16Container_values_DCValue(PyObject *o) {
  struct __pyx_obj_4pymc_16Container_values_DCValue *p = (struct __pyx_obj_4pymc_16Container_values_DCValue *)o;
  PyObject *t;
  t = p->_value; 
  p->_value = Py_None; Py_INCREF(Py_None);
  Py_XDECREF(t);
  t = p->val_obj; 
  p->val_obj = Py_None; Py_INCREF(Py_None);
  Py_XDECREF(t);
  return 0;
}

static struct PyMethodDef __pyx_methods_4pymc_16Container_values_DCValue[] = {
  {"run", (PyCFunction)__pyx_f_4pymc_16Container_values_7DCValue_run, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_DCValue = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
  #if Py_TPFLAGS_DEFAULT & Py_TPFLAGS_HAVE_INDEX
  0, /*nb_index*/
  #endif
};

static PySequenceMethods __pyx_tp_as_sequence_DCValue = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_DCValue = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_DCValue = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_4pymc_16Container_values_DCValue = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "pymc.Container_values.DCValue", /*tp_name*/
  sizeof(struct __pyx_obj_4pymc_16Container_values_DCValue), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_4pymc_16Container_values_DCValue, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_DCValue, /*tp_as_number*/
  &__pyx_tp_as_sequence_DCValue, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_DCValue, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_DCValue, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE|Py_TPFLAGS_HAVE_GC, /*tp_flags*/
  "\n    d = DCValue(container)\n    d.run()\n\n    run() method replaces DictContainers\'keys corresponding to variables and containers\n    with their values.\n    ", /*tp_doc*/
  __pyx_tp_traverse_4pymc_16Container_values_DCValue, /*tp_traverse*/
  __pyx_tp_clear_4pymc_16Container_values_DCValue, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_4pymc_16Container_values_DCValue, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  __pyx_f_4pymc_16Container_values_7DCValue___init__, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_4pymc_16Container_values_DCValue, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static PyObject *__pyx_tp_new_4pymc_16Container_values_OCValue(PyTypeObject *t, PyObject *a, PyObject *k) {
  struct __pyx_obj_4pymc_16Container_values_OCValue *p;
  PyObject *o = (*t->tp_alloc)(t, 0);
  if (!o) return 0;
  p = ((struct __pyx_obj_4pymc_16Container_values_OCValue *)o);
  p->_value = Py_None; Py_INCREF(Py_None);
  p->val_obj = Py_None; Py_INCREF(Py_None);
  return o;
}

static void __pyx_tp_dealloc_4pymc_16Container_values_OCValue(PyObject *o) {
  struct __pyx_obj_4pymc_16Container_values_OCValue *p = (struct __pyx_obj_4pymc_16Container_values_OCValue *)o;
  Py_XDECREF(p->_value);
  Py_XDECREF(p->val_obj);
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_4pymc_16Container_values_OCValue(PyObject *o, visitproc v, void *a) {
  int e;
  struct __pyx_obj_4pymc_16Container_values_OCValue *p = (struct __pyx_obj_4pymc_16Container_values_OCValue *)o;
  if (p->_value) {
    e = (*v)(p->_value, a); if (e) return e;
  }
  if (p->val_obj) {
    e = (*v)(p->val_obj, a); if (e) return e;
  }
  return 0;
}

static int __pyx_tp_clear_4pymc_16Container_values_OCValue(PyObject *o) {
  struct __pyx_obj_4pymc_16Container_values_OCValue *p = (struct __pyx_obj_4pymc_16Container_values_OCValue *)o;
  PyObject *t;
  t = p->_value; 
  p->_value = Py_None; Py_INCREF(Py_None);
  Py_XDECREF(t);
  t = p->val_obj; 
  p->val_obj = Py_None; Py_INCREF(Py_None);
  Py_XDECREF(t);
  return 0;
}

static struct PyMethodDef __pyx_methods_4pymc_16Container_values_OCValue[] = {
  {"run", (PyCFunction)__pyx_f_4pymc_16Container_values_7OCValue_run, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_OCValue = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
  #if Py_TPFLAGS_DEFAULT & Py_TPFLAGS_HAVE_INDEX
  0, /*nb_index*/
  #endif
};

static PySequenceMethods __pyx_tp_as_sequence_OCValue = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_OCValue = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_OCValue = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_4pymc_16Container_values_OCValue = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "pymc.Container_values.OCValue", /*tp_name*/
  sizeof(struct __pyx_obj_4pymc_16Container_values_OCValue), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_4pymc_16Container_values_OCValue, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_OCValue, /*tp_as_number*/
  &__pyx_tp_as_sequence_OCValue, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_OCValue, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_OCValue, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE|Py_TPFLAGS_HAVE_GC, /*tp_flags*/
  "\n    d = OCValue(container)\n    d.run()\n\n    run() method fills in value of container.\n    ", /*tp_doc*/
  __pyx_tp_traverse_4pymc_16Container_values_OCValue, /*tp_traverse*/
  __pyx_tp_clear_4pymc_16Container_values_OCValue, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_4pymc_16Container_values_OCValue, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  __pyx_f_4pymc_16Container_values_7OCValue___init__, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_4pymc_16Container_values_OCValue, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static PyObject *__pyx_tp_new_4pymc_16Container_values_ACValue(PyTypeObject *t, PyObject *a, PyObject *k) {
  struct __pyx_obj_4pymc_16Container_values_ACValue *p;
  PyObject *o = (*t->tp_alloc)(t, 0);
  if (!o) return 0;
  p = ((struct __pyx_obj_4pymc_16Container_values_ACValue *)o);
  p->_ravelledvalue = Py_None; Py_INCREF(Py_None);
  p->val_obj = Py_None; Py_INCREF(Py_None);
  return o;
}

static void __pyx_tp_dealloc_4pymc_16Container_values_ACValue(PyObject *o) {
  struct __pyx_obj_4pymc_16Container_values_ACValue *p = (struct __pyx_obj_4pymc_16Container_values_ACValue *)o;
  Py_XDECREF(p->_ravelledvalue);
  Py_XDECREF(p->val_obj);
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_4pymc_16Container_values_ACValue(PyObject *o, visitproc v, void *a) {
  int e;
  struct __pyx_obj_4pymc_16Container_values_ACValue *p = (struct __pyx_obj_4pymc_16Container_values_ACValue *)o;
  if (p->_ravelledvalue) {
    e = (*v)(p->_ravelledvalue, a); if (e) return e;
  }
  if (p->val_obj) {
    e = (*v)(p->val_obj, a); if (e) return e;
  }
  return 0;
}

static int __pyx_tp_clear_4pymc_16Container_values_ACValue(PyObject *o) {
  struct __pyx_obj_4pymc_16Container_values_ACValue *p = (struct __pyx_obj_4pymc_16Container_values_ACValue *)o;
  PyObject *t;
  t = p->_ravelledvalue; 
  p->_ravelledvalue = Py_None; Py_INCREF(Py_None);
  Py_XDECREF(t);
  t = p->val_obj; 
  p->val_obj = Py_None; Py_INCREF(Py_None);
  Py_XDECREF(t);
  return 0;
}

static struct PyMethodDef __pyx_methods_4pymc_16Container_values_ACValue[] = {
  {"run", (PyCFunction)__pyx_f_4pymc_16Container_values_7ACValue_run, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_ACValue = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
  #if Py_TPFLAGS_DEFAULT & Py_TPFLAGS_HAVE_INDEX
  0, /*nb_index*/
  #endif
};

static PySequenceMethods __pyx_tp_as_sequence_ACValue = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_ACValue = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_ACValue = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_4pymc_16Container_values_ACValue = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "pymc.Container_values.ACValue", /*tp_name*/
  sizeof(struct __pyx_obj_4pymc_16Container_values_ACValue), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_4pymc_16Container_values_ACValue, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_ACValue, /*tp_as_number*/
  &__pyx_tp_as_sequence_ACValue, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_ACValue, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_ACValue, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE|Py_TPFLAGS_HAVE_GC, /*tp_flags*/
  "\n    A = ACValue(container)\n    A.run()\n\n    run() method fills in value of ArrayContainer.\n    ", /*tp_doc*/
  __pyx_tp_traverse_4pymc_16Container_values_ACValue, /*tp_traverse*/
  __pyx_tp_clear_4pymc_16Container_values_ACValue, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_4pymc_16Container_values_ACValue, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  __pyx_f_4pymc_16Container_values_7ACValue___init__, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_4pymc_16Container_values_ACValue, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC initContainer_values(void); /*proto*/
PyMODINIT_FUNC initContainer_values(void) {
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  __pyx_init_filenames();
  __pyx_m = Py_InitModule4("Container_values", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  Py_INCREF(__pyx_m);
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  __pyx_type_4pymc_16Container_values_LCValue.tp_free = _PyObject_GC_Del;
  if (PyType_Ready(&__pyx_type_4pymc_16Container_values_LCValue) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 11; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "LCValue", (PyObject *)&__pyx_type_4pymc_16Container_values_LCValue) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 11; goto __pyx_L1;}
  __pyx_ptype_4pymc_16Container_values_LCValue = &__pyx_type_4pymc_16Container_values_LCValue;
  __pyx_type_4pymc_16Container_values_DCValue.tp_free = _PyObject_GC_Del;
  if (PyType_Ready(&__pyx_type_4pymc_16Container_values_DCValue) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 42; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "DCValue", (PyObject *)&__pyx_type_4pymc_16Container_values_DCValue) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 42; goto __pyx_L1;}
  __pyx_ptype_4pymc_16Container_values_DCValue = &__pyx_type_4pymc_16Container_values_DCValue;
  __pyx_type_4pymc_16Container_values_OCValue.tp_free = _PyObject_GC_Del;
  if (PyType_Ready(&__pyx_type_4pymc_16Container_values_OCValue) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 73; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "OCValue", (PyObject *)&__pyx_type_4pymc_16Container_values_OCValue) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 73; goto __pyx_L1;}
  __pyx_ptype_4pymc_16Container_values_OCValue = &__pyx_type_4pymc_16Container_values_OCValue;
  __pyx_type_4pymc_16Container_values_ACValue.tp_free = _PyObject_GC_Del;
  if (PyType_Ready(&__pyx_type_4pymc_16Container_values_ACValue) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "ACValue", (PyObject *)&__pyx_type_4pymc_16Container_values_ACValue) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 101; goto __pyx_L1;}
  __pyx_ptype_4pymc_16Container_values_ACValue = &__pyx_type_4pymc_16Container_values_ACValue;

  /* "/Users/anand/renearch/pymc-git/pymc/Container_values.pyx":1 */
  __pyx_1 = PyList_New(2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;}
  Py_INCREF(__pyx_n_Variable);
  PyList_SET_ITEM(__pyx_1, 0, __pyx_n_Variable);
  Py_INCREF(__pyx_n_ContainerBase);
  PyList_SET_ITEM(__pyx_1, 1, __pyx_n_ContainerBase);
  __pyx_2 = __Pyx_Import(__pyx_n_Node, __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyObject_GetAttr(__pyx_2, __pyx_n_Variable); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_Variable, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyObject_GetAttr(__pyx_2, __pyx_n_ContainerBase); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_ContainerBase, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/Users/anand/renearch/pymc-git/pymc/Container_values.pyx":2 */
  __pyx_2 = PyList_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;}
  Py_INCREF(__pyx_n_copy);
  PyList_SET_ITEM(__pyx_2, 0, __pyx_n_copy);
  __pyx_1 = __Pyx_Import(__pyx_n_copy, __pyx_2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_2 = PyObject_GetAttr(__pyx_1, __pyx_n_copy); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_copy, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/Users/anand/renearch/pymc-git/pymc/Container_values.pyx":3 */
  __pyx_1 = PyList_New(6); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; goto __pyx_L1;}
  Py_INCREF(__pyx_n_ndarray);
  PyList_SET_ITEM(__pyx_1, 0, __pyx_n_ndarray);
  Py_INCREF(__pyx_n_array);
  PyList_SET_ITEM(__pyx_1, 1, __pyx_n_array);
  Py_INCREF(__pyx_n_zeros);
  PyList_SET_ITEM(__pyx_1, 2, __pyx_n_zeros);
  Py_INCREF(__pyx_n_shape);
  PyList_SET_ITEM(__pyx_1, 3, __pyx_n_shape);
  Py_INCREF(__pyx_n_arange);
  PyList_SET_ITEM(__pyx_1, 4, __pyx_n_arange);
  Py_INCREF(__pyx_n_where);
  PyList_SET_ITEM(__pyx_1, 5, __pyx_n_where);
  __pyx_2 = __Pyx_Import(__pyx_n_numpy, __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyObject_GetAttr(__pyx_2, __pyx_n_ndarray); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_ndarray, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyObject_GetAttr(__pyx_2, __pyx_n_array); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_array, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyObject_GetAttr(__pyx_2, __pyx_n_zeros); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_zeros, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyObject_GetAttr(__pyx_2, __pyx_n_shape); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_shape, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyObject_GetAttr(__pyx_2, __pyx_n_arange); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_arange, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_1 = PyObject_GetAttr(__pyx_2, __pyx_n_where); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_where, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 3; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/Users/anand/renearch/pymc-git/pymc/Container_values.pyx":120 */
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("pymc.Container_values");
}

static char *__pyx_filenames[] = {
  "Container_values.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static int __Pyx_SetItemInt(PyObject *o, Py_ssize_t i, PyObject *v) {
    PyTypeObject *t = o->ob_type;
    int r;
    if (t->tp_as_sequence && t->tp_as_sequence->sq_item)
        r = PySequence_SetItem(o, i, v);
    else {
        PyObject *j = PyInt_FromLong(i);
        if (!j)
            return -1;
        r = PyObject_SetItem(o, j, v);
        Py_DECREF(j);
    }
    return r;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        if (!*t->p)
            return -1;
        if (t->i)
            PyString_InternInPlace(t->p);
        ++t;
    }
    return 0;
}

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list) {
    PyObject *__import__ = 0;
    PyObject *empty_list = 0;
    PyObject *module = 0;
    PyObject *global_dict = 0;
    PyObject *empty_dict = 0;
    PyObject *list;
    __import__ = PyObject_GetAttrString(__pyx_b, "__import__");
    if (!__import__)
        goto bad;
    if (from_list)
        list = from_list;
    else {
        empty_list = PyList_New(0);
        if (!empty_list)
            goto bad;
        list = empty_list;
    }
    global_dict = PyModule_GetDict(__pyx_m);
    if (!global_dict)
        goto bad;
    empty_dict = PyDict_New();
    if (!empty_dict)
        goto bad;
    module = PyObject_CallFunction(__import__, "OOOO",
        name, global_dict, empty_dict, list);
bad:
    Py_XDECREF(empty_list);
    Py_XDECREF(__import__);
    Py_XDECREF(empty_dict);
    return module;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
