name: "Pull Request Labeler"
on:
- pull_request_target

jobs:
  sync:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Sync labels with closing issues
      uses: wd60622/closing-labels@v0.0.3
      with:
        exclude: "help wanted,needs info,beginner friendly"
      env:
        GH_TOKEN: ${{ github.token }}
